coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

ignore:
  - "examples/**"
  - "tests/**"
  - "internal/testhelper/**"
