// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package audit

import "fmt"

// LabelInfo describes a sensitivity label defined in the taxonomy.
type LabelInfo struct {
	Name        string // label name, e.g., "pii"
	Description string // human-readable explanation
}

// FieldInfo describes a single field on an audit event type.
type FieldInfo struct {
	Name     string      // field name, e.g., "email"
	Labels   []LabelInfo // sensitivity labels on this field
	Required bool        // true if the field must be present
}

// CategoryInfo describes a category an event type belongs to.
type CategoryInfo struct {
	Severity *int   // category-level severity, nil if not set
	Name     string // category name, e.g., "write"
}

// Event represents a typed audit event with its event type and fields.
// Implementations are generated by audit-gen for compile-time field
// safety. For dynamic use without code generation, see [NewEvent].
//
// The interface is intentionally minimal. Generated builder structs
// from audit-gen carry richer metadata (per-field descriptors,
// categories, description) accessible via type assertion on the
// concrete type.
type Event interface {
	// EventType returns the event type name (e.g., "user_create").
	EventType() string
	// Fields returns the event's field key-value pairs.
	Fields() Fields
}

// basicEvent implements [Event] for consumers who do not use code
// generation. Created via [NewEvent].
type basicEvent struct {
	fields    Fields
	eventType string
}

// NewEvent creates an untyped audit event. Prefer generated typed
// builders from audit-gen for compile-time field safety. This function
// exists for consumers who construct events dynamically or do not use
// code generation.
func NewEvent(eventType string, fields Fields) Event {
	return &basicEvent{
		eventType: eventType,
		fields:    fields,
	}
}

func (e *basicEvent) EventType() string { return e.eventType }
func (e *basicEvent) Fields() Fields    { return e.fields }

// NewEventKV creates an audit event from alternating key-value pairs,
// following the [log/slog] convention:
//
//	audit.NewEventKV("user_create", "outcome", "success", "actor_id", "alice")
//
// NewEventKV panics if keysAndValues has an odd number of elements or
// if any key is not a string. These are always programming errors, not
// runtime conditions — the same convention as [slog.Info].
func NewEventKV(eventType string, keysAndValues ...any) Event {
	if len(keysAndValues)%2 != 0 {
		panic(fmt.Sprintf("audit: NewEventKV requires even number of arguments, got %d", len(keysAndValues)))
	}
	fields := make(Fields, len(keysAndValues)/2)
	for i := 0; i < len(keysAndValues); i += 2 {
		key, ok := keysAndValues[i].(string)
		if !ok {
			panic(fmt.Sprintf("audit: NewEventKV key at index %d must be string, got %T", i, keysAndValues[i]))
		}
		fields[key] = keysAndValues[i+1]
	}
	return NewEvent(eventType, fields)
}

// EventHandle is a pre-validated reference to a registered event type.
// It carries the event type name and a reference to the owning [Logger],
// enabling audit calls without repeated string lookup. Use generated
// builders for static event types; use [Logger.Handle] or
// [Logger.MustHandle] for dynamically-determined event types (e.g.
// event type names from configuration or a database).
type EventHandle struct {
	logger *Logger
	name   string
}

// Audit emits an audit event using this handle's bound event type.
// This method bypasses [NewEvent] to avoid a per-event heap allocation
// from interface escape, calling the internal audit path directly.
func (e *EventHandle) Audit(fields Fields) error {
	return e.logger.auditInternal(e.name, fields)
}

// AuditEvent emits an [Event] (typically a generated builder) using
// the logger bound to this handle. Unlike [EventHandle.Audit], the
// event type is taken from evt.EventType(), not from the handle's
// bound type — the handle provides the logger binding only. This
// method accepts any [Event] implementation, making it composable
// with code-generated typed builders.
func (e *EventHandle) AuditEvent(evt Event) error {
	return e.logger.AuditEvent(evt)
}

// EventType returns the event type name this handle represents.
func (e *EventHandle) EventType() string {
	return e.name
}

// auditEntry is the internal representation of an audit event as it
// travels through the async channel. It is not exported.
type auditEntry struct {
	fields    Fields
	eventType string
}
