// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package audit

import "fmt"

// LabelInfo describes a sensitivity label defined in the taxonomy.
type LabelInfo struct {
	Name        string // label name, e.g., "pii"
	Description string // human-readable explanation
}

// FieldInfo describes a single field on an audit event type.
type FieldInfo struct {
	Name     string      // field name, e.g., "email"
	Labels   []LabelInfo // sensitivity labels on this field
	Required bool        // true if the field must be present
}

// CategoryInfo describes a category an event type belongs to.
type CategoryInfo struct {
	Severity *int   // category-level severity, nil if not set
	Name     string // category name, e.g., "write"
}

// Event represents a typed audit event with its event type and fields.
// Implementations are generated by audit-gen for compile-time field
// safety. For dynamic use without code generation, see [NewEvent].
//
// The interface is intentionally minimal. Generated builder structs
// from audit-gen carry richer metadata (per-field descriptors,
// categories, description) accessible via type assertion on the
// concrete type.
type Event interface {
	// EventType returns the event type name (e.g., "user_create").
	EventType() string
	// Fields returns the event's field key-value pairs.
	Fields() Fields
}

// basicEvent implements [Event] for consumers who do not use code
// generation. Created via [NewEvent].
type basicEvent struct {
	fields    Fields
	eventType string
}

// NewEvent creates an untyped audit event. Prefer generated typed
// builders from audit-gen for compile-time field safety. This function
// exists for consumers who construct events dynamically or do not use
// code generation.
//
// Allocation note: each call allocates one basicEvent on the heap
// because the returned [Event] interface value forces the pointer to
// escape. For high-throughput callers whose event type is known but
// dynamic (from configuration, a database, or a plugin), prefer
// [EventHandle] — it pre-validates the event type once and emits
// without the per-call basicEvent allocation. See [Auditor.Handle]
// and [Auditor.MustHandle].
func NewEvent(eventType string, fields Fields) Event {
	return &basicEvent{
		eventType: eventType,
		fields:    fields,
	}
}

func (e *basicEvent) EventType() string { return e.eventType }
func (e *basicEvent) Fields() Fields    { return e.fields }

// NewEventKV creates an audit event from alternating key-value pairs,
// following the [log/slog] convention:
//
//	audit.NewEventKV("user_create", "outcome", "success", "actor_id", "alice")
//
// NewEventKV panics if keysAndValues has an odd number of elements or
// if any key is not a string. These are always programming errors, not
// runtime conditions — the same convention as [slog.Info].
//
// Allocation note: NewEventKV allocates the intermediate [Fields] map
// plus the basicEvent returned by [NewEvent] — two heap allocations
// per call (plus any-boxing of non-string values). For high-throughput
// callers, prefer generated typed builders (zero caller-side
// allocations after warm-up) or [EventHandle] for dynamic event types.
func NewEventKV(eventType string, keysAndValues ...any) Event {
	if len(keysAndValues)%2 != 0 {
		panic(fmt.Sprintf("audit: NewEventKV requires even number of arguments, got %d", len(keysAndValues)))
	}
	fields := make(Fields, len(keysAndValues)/2)
	for i := 0; i < len(keysAndValues); i += 2 {
		key, ok := keysAndValues[i].(string)
		if !ok {
			panic(fmt.Sprintf("audit: NewEventKV key at index %d must be string, got %T", i, keysAndValues[i]))
		}
		fields[key] = keysAndValues[i+1]
	}
	return NewEvent(eventType, fields)
}

// EventHandle is a pre-validated reference to a registered event type.
// It is the recommended emission path when the event type is known at
// startup but not at compile time — for example, event type names
// pulled from configuration, a database, or a plugin registry.
//
// Obtain one handle per event type at startup via [Auditor.Handle]
// (returns an error) or [Auditor.MustHandle] (panics on unknown event
// type), cache it, and emit via [EventHandle.Audit] on each event.
// The handle validates the event type once at construction; per-event
// calls go straight into the audit pipeline without re-validating the
// name and without the basicEvent heap allocation paid by
// [NewEvent].
//
// For event types known at compile time, prefer generated typed
// builders from audit-gen — they add compile-time field safety and
// implement [FieldsDonor] for the zero-allocation drain-side fast
// path.
type EventHandle struct {
	auditor *Auditor
	name    string
}

// Audit emits an audit event using this handle's bound event type.
// Zero per-event caller-side allocations (no basicEvent
// construction, no [Event] interface escape) — the internal audit
// path is called directly. For the zero-drain-side-allocations fast
// path (the [FieldsDonor] contract), emit a generated typed builder
// directly via [Auditor.AuditEvent].
func (e *EventHandle) Audit(fields Fields) error {
	return e.auditor.auditInternal(e.name, fields)
}

// AuditEvent emits an [Event] (typically a generated builder) using
// the auditor bound to this handle. Unlike [EventHandle.Audit], the
// event type is taken from evt.EventType(), not from the handle's
// bound type — the handle provides the auditor binding only. This
// method accepts any [Event] implementation, making it composable
// with code-generated typed builders.
//
// Allocation note: this method takes the standard [Auditor.AuditEvent]
// path. Allocation behaviour depends on evt: generated builders that
// implement [FieldsDonor] reach 0 drain-side allocs per event; plain
// [Event] values (including [NewEvent] output) pay the defensive-copy
// cost described in [docs/performance.md].
func (e *EventHandle) AuditEvent(evt Event) error {
	return e.auditor.AuditEvent(evt)
}

// EventType returns the event type name this handle represents.
func (e *EventHandle) EventType() string {
	return e.name
}

// FieldsDonor is an optional extension interface that the audit
// pipeline checks via type assertion in [Auditor.AuditEvent]. When an
// [Event] also implements FieldsDonor, the auditor takes ownership of
// the [Fields] map returned by [Event.Fields] — no defensive copy.
//
// # Contract
//
// Implementers MUST NOT mutate or retain the returned Fields after
// [Event.Fields] is called by the auditor:
//
//   - The auditor merges standard-field defaults INTO the returned
//     map and the formatters then read from it across multiple
//     outputs.
//   - Re-using the same Event instance for a second [Auditor.AuditEvent]
//     call is undefined behaviour. The first call's defaults remain in
//     the map; subsequent calls would observe stale state.
//
// # Sentinel
//
// The unexported [donateFields] sentinel method prevents third-party
// implementation outside the audit-gen toolchain. Generated builders
// emit the sentinel; consumer-defined Event types and [NewEvent]
// stay on the defensive-copy slow path.
//
// See [docs/adr/0001-fields-ownership-contract.md] for the design
// rationale and benchmarks (#497).
type FieldsDonor interface {
	Event
	donateFields()
}

// auditEntry is the internal representation of an audit event as it
// travels through the async channel. It is not exported.
type auditEntry struct {
	fields    Fields
	eventType string
	// donated is true when fields was supplied by a [FieldsDonor]
	// (the caller's map). Pool-return must be skipped — the map
	// belongs to the donor, not the auditor's fieldsPool. donated is
	// false on the defensive-copy slow path; the existing pool-return
	// behaviour applies (#497).
	donated bool
}
