// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package audit

import "errors"

// LabelInfo describes a sensitivity label defined in the taxonomy.
type LabelInfo struct {
	Name        string // label name, e.g., "pii"
	Description string // human-readable explanation
}

// FieldInfo describes a single field on an audit event type.
type FieldInfo struct {
	Name     string      // field name, e.g., "email"
	Labels   []LabelInfo // sensitivity labels on this field
	Required bool        // true if the field must be present
}

// CategoryInfo describes a category an event type belongs to.
type CategoryInfo struct {
	Severity *int   // category-level severity, nil if not set
	Name     string // category name, e.g., "write"
}

// Event represents a typed audit event with its event type and fields.
// Implementations are generated by audit-gen for compile-time field
// safety. For dynamic use without code generation, see [NewEvent].
//
// The interface is intentionally minimal. Richer metadata (per-field
// descriptors, categories, description) lives on the generated builder
// structs directly, accessible via the concrete type.
type Event interface {
	// EventType returns the event type name (e.g., "user_create").
	EventType() string
	// Fields returns the event's field key-value pairs.
	Fields() Fields
}

// basicEvent implements [Event] for consumers who do not use code
// generation. Created via [NewEvent].
type basicEvent struct {
	fields    Fields
	eventType string
}

// NewEvent creates an untyped audit event. Prefer generated typed
// builders from audit-gen for compile-time field safety. This function
// exists for consumers who construct events dynamically or do not use
// code generation.
func NewEvent(eventType string, fields Fields) Event {
	return &basicEvent{
		eventType: eventType,
		fields:    fields,
	}
}

func (e *basicEvent) EventType() string { return e.eventType }
func (e *basicEvent) Fields() Fields    { return e.fields }

// EventType is a handle for a registered audit event type. It carries
// the event type name and a reference to the owning [Logger], enabling
// audit calls without repeated string lookup. Obtain a handle via
// [Logger.Handle] or [Logger.MustHandle].
type EventType struct {
	logger *Logger
	name   string
}

// Audit emits an audit event using this handle's bound event type.
// Fields are wrapped in [NewEvent] internally.
func (e *EventType) Audit(fields Fields) error {
	return e.logger.AuditEvent(NewEvent(e.name, fields))
}

// Name returns the event type name this handle represents.
func (e *EventType) Name() string {
	return e.name
}

// auditEntry is the internal representation of an audit event as it
// travels through the async channel. It is not exported.
type auditEntry struct {
	fields    Fields
	eventType string
}

// ErrHandleNotFound is returned by [Logger.Handle], and wrapped in
// the panic value of [Logger.MustHandle], when the requested event
// type is not registered in the taxonomy.
var ErrHandleNotFound = errors.New("audit: event type not found")
