// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import (
	"time"

	"github.com/axonops/audit"
)

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	EventLoginFailure = "login_failure"
	EventLoginSuccess = "login_success"
	EventUserCreate   = "user_create"
	EventUserUpdate   = "user_update"
)

// Category constants — use with Auditor.EnableCategory and
// Auditor.DisableCategory.
const (
	CategoryAccount  = "account"
	CategorySecurity = "security"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventLoginFailure: {
		Required: []string{FieldActorID, FieldOutcome, FieldReason, FieldSourceIP},
		Optional: []string{},
	},
	EventLoginSuccess: {
		Required: []string{FieldActorID, FieldOutcome, FieldSourceIP},
		Optional: []string{},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome, FieldTargetID, FieldTargetType},
		Optional: []string{},
	},
	EventUserUpdate: {
		Required: []string{FieldActorID, FieldOutcome, FieldTargetID},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryAccount:  {EventUserCreate, EventUserUpdate},
	CategorySecurity: {EventLoginFailure, EventLoginSuccess},
}

// LoginFailureFields describes every field on [EventLoginFailure] events.
type LoginFailureFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Reason     audit.FieldInfo // required
	SourceIP   audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// LoginFailureEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type LoginFailureEvent struct {
	fields audit.Fields
}

// NewLoginFailureEvent creates a EventLoginFailure event with required fields.
func NewLoginFailureEvent(actorID string, outcome string, reason string, sourceIP string) *LoginFailureEvent {
	return &LoginFailureEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldOutcome:  outcome,
		FieldReason:   reason,
		FieldSourceIP: sourceIP,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *LoginFailureEvent) SetAction(v string) *LoginFailureEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *LoginFailureEvent) SetActorUID(v string) *LoginFailureEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *LoginFailureEvent) SetDestHost(v string) *LoginFailureEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *LoginFailureEvent) SetDestIP(v string) *LoginFailureEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *LoginFailureEvent) SetDestPort(v int) *LoginFailureEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *LoginFailureEvent) SetEndTime(v time.Time) *LoginFailureEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *LoginFailureEvent) SetFileHash(v string) *LoginFailureEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *LoginFailureEvent) SetFileName(v string) *LoginFailureEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *LoginFailureEvent) SetFilePath(v string) *LoginFailureEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *LoginFailureEvent) SetFileSize(v int) *LoginFailureEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *LoginFailureEvent) SetMessage(v string) *LoginFailureEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *LoginFailureEvent) SetMethod(v string) *LoginFailureEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *LoginFailureEvent) SetPath(v string) *LoginFailureEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *LoginFailureEvent) SetProtocol(v string) *LoginFailureEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *LoginFailureEvent) SetReferrer(v string) *LoginFailureEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *LoginFailureEvent) SetRequestID(v string) *LoginFailureEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *LoginFailureEvent) SetRole(v string) *LoginFailureEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *LoginFailureEvent) SetSessionID(v string) *LoginFailureEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *LoginFailureEvent) SetSourceHost(v string) *LoginFailureEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *LoginFailureEvent) SetSourcePort(v int) *LoginFailureEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *LoginFailureEvent) SetStartTime(v time.Time) *LoginFailureEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *LoginFailureEvent) SetTargetID(v string) *LoginFailureEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *LoginFailureEvent) SetTargetRole(v string) *LoginFailureEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *LoginFailureEvent) SetTargetType(v string) *LoginFailureEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *LoginFailureEvent) SetTargetUID(v string) *LoginFailureEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *LoginFailureEvent) SetTransport(v string) *LoginFailureEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *LoginFailureEvent) SetUserAgent(v string) *LoginFailureEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *LoginFailureEvent) EventType() string { return EventLoginFailure }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *LoginFailureEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *LoginFailureEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *LoginFailureEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *LoginFailureEvent) FieldInfo() LoginFailureFields {
	return LoginFailureFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:     audit.FieldInfo{Name: FieldReason, Required: true},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *LoginFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [LoginFailureFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *LoginFailureEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldReason:     {Name: FieldReason, Required: true},
		FieldSourceIP:   {Name: FieldSourceIP, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// LoginSuccessFields describes every field on [EventLoginSuccess] events.
type LoginSuccessFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	SourceIP   audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// LoginSuccessEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type LoginSuccessEvent struct {
	fields audit.Fields
}

// NewLoginSuccessEvent creates a EventLoginSuccess event with required fields.
func NewLoginSuccessEvent(actorID string, outcome string, sourceIP string) *LoginSuccessEvent {
	return &LoginSuccessEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldOutcome:  outcome,
		FieldSourceIP: sourceIP,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *LoginSuccessEvent) SetAction(v string) *LoginSuccessEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *LoginSuccessEvent) SetActorUID(v string) *LoginSuccessEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *LoginSuccessEvent) SetDestHost(v string) *LoginSuccessEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *LoginSuccessEvent) SetDestIP(v string) *LoginSuccessEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *LoginSuccessEvent) SetDestPort(v int) *LoginSuccessEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *LoginSuccessEvent) SetEndTime(v time.Time) *LoginSuccessEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *LoginSuccessEvent) SetFileHash(v string) *LoginSuccessEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *LoginSuccessEvent) SetFileName(v string) *LoginSuccessEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *LoginSuccessEvent) SetFilePath(v string) *LoginSuccessEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *LoginSuccessEvent) SetFileSize(v int) *LoginSuccessEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *LoginSuccessEvent) SetMessage(v string) *LoginSuccessEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *LoginSuccessEvent) SetMethod(v string) *LoginSuccessEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *LoginSuccessEvent) SetPath(v string) *LoginSuccessEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *LoginSuccessEvent) SetProtocol(v string) *LoginSuccessEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *LoginSuccessEvent) SetReason(v string) *LoginSuccessEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *LoginSuccessEvent) SetReferrer(v string) *LoginSuccessEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *LoginSuccessEvent) SetRequestID(v string) *LoginSuccessEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *LoginSuccessEvent) SetRole(v string) *LoginSuccessEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *LoginSuccessEvent) SetSessionID(v string) *LoginSuccessEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *LoginSuccessEvent) SetSourceHost(v string) *LoginSuccessEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *LoginSuccessEvent) SetSourcePort(v int) *LoginSuccessEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *LoginSuccessEvent) SetStartTime(v time.Time) *LoginSuccessEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *LoginSuccessEvent) SetTargetID(v string) *LoginSuccessEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *LoginSuccessEvent) SetTargetRole(v string) *LoginSuccessEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *LoginSuccessEvent) SetTargetType(v string) *LoginSuccessEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *LoginSuccessEvent) SetTargetUID(v string) *LoginSuccessEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *LoginSuccessEvent) SetTransport(v string) *LoginSuccessEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *LoginSuccessEvent) SetUserAgent(v string) *LoginSuccessEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *LoginSuccessEvent) EventType() string { return EventLoginSuccess }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *LoginSuccessEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *LoginSuccessEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *LoginSuccessEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *LoginSuccessEvent) FieldInfo() LoginSuccessFields {
	return LoginSuccessFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *LoginSuccessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [LoginSuccessFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *LoginSuccessEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldSourceIP:   {Name: FieldSourceIP, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	TargetID   audit.FieldInfo // required
	TargetType audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserCreateEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID string, outcome string, targetID string, targetType string) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID:    actorID,
		FieldOutcome:    outcome,
		FieldTargetID:   targetID,
		FieldTargetType: targetType,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *UserCreateEvent) SetAction(v string) *UserCreateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserCreateEvent) SetActorUID(v string) *UserCreateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserCreateEvent) SetDestHost(v string) *UserCreateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserCreateEvent) SetDestIP(v string) *UserCreateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserCreateEvent) SetDestPort(v int) *UserCreateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserCreateEvent) SetEndTime(v time.Time) *UserCreateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserCreateEvent) SetFileHash(v string) *UserCreateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserCreateEvent) SetFileName(v string) *UserCreateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserCreateEvent) SetFilePath(v string) *UserCreateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserCreateEvent) SetFileSize(v int) *UserCreateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserCreateEvent) SetMessage(v string) *UserCreateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserCreateEvent) SetMethod(v string) *UserCreateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserCreateEvent) SetPath(v string) *UserCreateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserCreateEvent) SetProtocol(v string) *UserCreateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserCreateEvent) SetReason(v string) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserCreateEvent) SetReferrer(v string) *UserCreateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserCreateEvent) SetRequestID(v string) *UserCreateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserCreateEvent) SetRole(v string) *UserCreateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserCreateEvent) SetSessionID(v string) *UserCreateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserCreateEvent) SetSourceHost(v string) *UserCreateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserCreateEvent) SetSourceIP(v string) *UserCreateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserCreateEvent) SetSourcePort(v int) *UserCreateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserCreateEvent) SetStartTime(v time.Time) *UserCreateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserCreateEvent) SetTargetRole(v string) *UserCreateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserCreateEvent) SetTargetUID(v string) *UserCreateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserCreateEvent) SetTransport(v string) *UserCreateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserCreateEvent) SetUserAgent(v string) *UserCreateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *UserCreateEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID:   audit.FieldInfo{Name: FieldTargetID, Required: true},
		TargetType: audit.FieldInfo{Name: FieldTargetType, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryAccount},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [UserCreateFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *UserCreateEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldTargetID:   {Name: FieldTargetID, Required: true},
		FieldTargetType: {Name: FieldTargetType, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// UserUpdateFields describes every field on [EventUserUpdate] events.
type UserUpdateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	TargetID   audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserUpdateEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserUpdateEvent struct {
	fields audit.Fields
}

// NewUserUpdateEvent creates a EventUserUpdate event with required fields.
func NewUserUpdateEvent(actorID string, outcome string, targetID string) *UserUpdateEvent {
	return &UserUpdateEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldOutcome:  outcome,
		FieldTargetID: targetID,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *UserUpdateEvent) SetAction(v string) *UserUpdateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserUpdateEvent) SetActorUID(v string) *UserUpdateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserUpdateEvent) SetDestHost(v string) *UserUpdateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserUpdateEvent) SetDestIP(v string) *UserUpdateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserUpdateEvent) SetDestPort(v int) *UserUpdateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserUpdateEvent) SetEndTime(v time.Time) *UserUpdateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserUpdateEvent) SetFileHash(v string) *UserUpdateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserUpdateEvent) SetFileName(v string) *UserUpdateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserUpdateEvent) SetFilePath(v string) *UserUpdateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserUpdateEvent) SetFileSize(v int) *UserUpdateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserUpdateEvent) SetMessage(v string) *UserUpdateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserUpdateEvent) SetMethod(v string) *UserUpdateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserUpdateEvent) SetPath(v string) *UserUpdateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserUpdateEvent) SetProtocol(v string) *UserUpdateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserUpdateEvent) SetReason(v string) *UserUpdateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserUpdateEvent) SetReferrer(v string) *UserUpdateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserUpdateEvent) SetRequestID(v string) *UserUpdateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserUpdateEvent) SetRole(v string) *UserUpdateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserUpdateEvent) SetSessionID(v string) *UserUpdateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserUpdateEvent) SetSourceHost(v string) *UserUpdateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserUpdateEvent) SetSourceIP(v string) *UserUpdateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserUpdateEvent) SetSourcePort(v int) *UserUpdateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserUpdateEvent) SetStartTime(v time.Time) *UserUpdateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserUpdateEvent) SetTargetRole(v string) *UserUpdateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserUpdateEvent) SetTargetType(v string) *UserUpdateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserUpdateEvent) SetTargetUID(v string) *UserUpdateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserUpdateEvent) SetTransport(v string) *UserUpdateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserUpdateEvent) SetUserAgent(v string) *UserUpdateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserUpdateEvent) EventType() string { return EventUserUpdate }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *UserUpdateEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *UserUpdateEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *UserUpdateEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserUpdateEvent) FieldInfo() UserUpdateFields {
	return UserUpdateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID:   audit.FieldInfo{Name: FieldTargetID, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserUpdateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryAccount},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [UserUpdateFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *UserUpdateEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldTargetID:   {Name: FieldTargetID, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}
