// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventPaymentProcess — A payment was processed
	EventPaymentProcess = "payment_process"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryWrite = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldAmount     = "amount"
	FieldCardExpiry = "card_expiry"
	FieldCardNumber = "card_number"
	FieldDepartment = "department"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldEmail      = "email"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldPhone      = "phone"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
	FieldUserName   = "user_name"
)

// Sensitivity label constants — use with exclude_labels
// in output configuration.
const (
	// LabelFinancial — Financial and payment data
	LabelFinancial = "financial"
	// LabelPii — Personally identifiable information
	LabelPii = "pii"
)

// FieldLabels maps field names to the sensitivity labels they carry.
// Resolved from all three mechanisms: explicit annotation, global
// field mapping, and regex patterns.
var FieldLabels = map[string][]string{
	FieldCardExpiry: {LabelFinancial},
	FieldCardNumber: {LabelFinancial},
	FieldEmail:      {LabelPii},
	FieldPhone:      {LabelPii},
	FieldUserName:   {LabelPii},
}

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventPaymentProcess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldAmount, FieldCardExpiry, FieldCardNumber},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldDepartment, FieldEmail, FieldPhone, FieldUserName},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryWrite: {EventPaymentProcess, EventUserCreate},
}

// PaymentProcessFields describes every field on [EventPaymentProcess] events.
type PaymentProcessFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Amount     audit.FieldInfo // optional
	CardExpiry audit.FieldInfo // optional
	CardNumber audit.FieldInfo // optional
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// PaymentProcessEvent builds a type-safe audit event: A payment was processed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type PaymentProcessEvent struct {
	fields audit.Fields
}

// NewPaymentProcessEvent creates a EventPaymentProcess event with required fields.
func NewPaymentProcessEvent(actorID string, outcome string) *PaymentProcessEvent {
	return &PaymentProcessEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetAmount sets the FieldAmount field.
func (e *PaymentProcessEvent) SetAmount(v any) *PaymentProcessEvent {
	e.fields[FieldAmount] = v
	return e
}

// SetCardExpiry sets the FieldCardExpiry field.
// Sensitivity label: LabelFinancial — Financial and payment data
func (e *PaymentProcessEvent) SetCardExpiry(v any) *PaymentProcessEvent {
	e.fields[FieldCardExpiry] = v
	return e
}

// SetCardNumber sets the FieldCardNumber field.
// Sensitivity label: LabelFinancial — Financial and payment data
func (e *PaymentProcessEvent) SetCardNumber(v any) *PaymentProcessEvent {
	e.fields[FieldCardNumber] = v
	return e
}

// SetAction sets the reserved standard field "action".
func (e *PaymentProcessEvent) SetAction(v string) *PaymentProcessEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *PaymentProcessEvent) SetActorUID(v string) *PaymentProcessEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *PaymentProcessEvent) SetDestHost(v string) *PaymentProcessEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *PaymentProcessEvent) SetDestIP(v string) *PaymentProcessEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *PaymentProcessEvent) SetDestPort(v int) *PaymentProcessEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *PaymentProcessEvent) SetEndTime(v string) *PaymentProcessEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *PaymentProcessEvent) SetFileHash(v string) *PaymentProcessEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *PaymentProcessEvent) SetFileName(v string) *PaymentProcessEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *PaymentProcessEvent) SetFilePath(v string) *PaymentProcessEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *PaymentProcessEvent) SetFileSize(v int) *PaymentProcessEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *PaymentProcessEvent) SetMessage(v string) *PaymentProcessEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *PaymentProcessEvent) SetMethod(v string) *PaymentProcessEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *PaymentProcessEvent) SetPath(v string) *PaymentProcessEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *PaymentProcessEvent) SetProtocol(v string) *PaymentProcessEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *PaymentProcessEvent) SetReason(v string) *PaymentProcessEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *PaymentProcessEvent) SetReferrer(v string) *PaymentProcessEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *PaymentProcessEvent) SetRequestID(v string) *PaymentProcessEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *PaymentProcessEvent) SetRole(v string) *PaymentProcessEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *PaymentProcessEvent) SetSessionID(v string) *PaymentProcessEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *PaymentProcessEvent) SetSourceHost(v string) *PaymentProcessEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *PaymentProcessEvent) SetSourceIP(v string) *PaymentProcessEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *PaymentProcessEvent) SetSourcePort(v int) *PaymentProcessEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *PaymentProcessEvent) SetStartTime(v string) *PaymentProcessEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *PaymentProcessEvent) SetTargetID(v string) *PaymentProcessEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *PaymentProcessEvent) SetTargetRole(v string) *PaymentProcessEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *PaymentProcessEvent) SetTargetType(v string) *PaymentProcessEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *PaymentProcessEvent) SetTargetUID(v string) *PaymentProcessEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *PaymentProcessEvent) SetTransport(v string) *PaymentProcessEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *PaymentProcessEvent) SetUserAgent(v string) *PaymentProcessEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *PaymentProcessEvent) EventType() string { return EventPaymentProcess }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *PaymentProcessEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *PaymentProcessEvent) Description() string { return "A payment was processed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *PaymentProcessEvent) FieldInfo() PaymentProcessFields {
	return PaymentProcessFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Amount:     audit.FieldInfo{Name: FieldAmount},
		CardExpiry: audit.FieldInfo{Name: FieldCardExpiry, Labels: []audit.LabelInfo{{Name: LabelFinancial, Description: "Financial and payment data"}}},
		CardNumber: audit.FieldInfo{Name: FieldCardNumber, Labels: []audit.LabelInfo{{Name: LabelFinancial, Description: "Financial and payment data"}}},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *PaymentProcessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Department audit.FieldInfo // optional
	Email      audit.FieldInfo // optional
	Phone      audit.FieldInfo // optional
	UserName   audit.FieldInfo // optional
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID string, outcome string) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetDepartment sets the FieldDepartment field.
func (e *UserCreateEvent) SetDepartment(v any) *UserCreateEvent {
	e.fields[FieldDepartment] = v
	return e
}

// SetEmail sets the FieldEmail field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetEmail(v any) *UserCreateEvent {
	e.fields[FieldEmail] = v
	return e
}

// SetPhone sets the FieldPhone field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetPhone(v any) *UserCreateEvent {
	e.fields[FieldPhone] = v
	return e
}

// SetUserName sets the FieldUserName field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetUserName(v any) *UserCreateEvent {
	e.fields[FieldUserName] = v
	return e
}

// SetAction sets the reserved standard field "action".
func (e *UserCreateEvent) SetAction(v string) *UserCreateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserCreateEvent) SetActorUID(v string) *UserCreateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserCreateEvent) SetDestHost(v string) *UserCreateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserCreateEvent) SetDestIP(v string) *UserCreateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserCreateEvent) SetDestPort(v int) *UserCreateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserCreateEvent) SetEndTime(v string) *UserCreateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserCreateEvent) SetFileHash(v string) *UserCreateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserCreateEvent) SetFileName(v string) *UserCreateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserCreateEvent) SetFilePath(v string) *UserCreateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserCreateEvent) SetFileSize(v int) *UserCreateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserCreateEvent) SetMessage(v string) *UserCreateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserCreateEvent) SetMethod(v string) *UserCreateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserCreateEvent) SetPath(v string) *UserCreateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserCreateEvent) SetProtocol(v string) *UserCreateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserCreateEvent) SetReason(v string) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserCreateEvent) SetReferrer(v string) *UserCreateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserCreateEvent) SetRequestID(v string) *UserCreateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserCreateEvent) SetRole(v string) *UserCreateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserCreateEvent) SetSessionID(v string) *UserCreateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserCreateEvent) SetSourceHost(v string) *UserCreateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserCreateEvent) SetSourceIP(v string) *UserCreateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserCreateEvent) SetSourcePort(v int) *UserCreateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserCreateEvent) SetStartTime(v string) *UserCreateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *UserCreateEvent) SetTargetID(v string) *UserCreateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserCreateEvent) SetTargetRole(v string) *UserCreateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserCreateEvent) SetTargetType(v string) *UserCreateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserCreateEvent) SetTargetUID(v string) *UserCreateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserCreateEvent) SetTransport(v string) *UserCreateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserCreateEvent) SetUserAgent(v string) *UserCreateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Department: audit.FieldInfo{Name: FieldDepartment},
		Email:      audit.FieldInfo{Name: FieldEmail, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
		Phone:      audit.FieldInfo{Name: FieldPhone, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
		UserName:   audit.FieldInfo{Name: FieldUserName, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}
