// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthLogin — User authenticated successfully
	EventAuthLogin = "auth_login"
	// EventAuthLogout — User ended their session
	EventAuthLogout = "auth_logout"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthLogin: {
		Required: []string{FieldActorID, FieldMethod, FieldOutcome},
		Optional: []string{},
	},
	EventAuthLogout: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome, FieldTargetID},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategorySecurity: {EventAuthLogin, EventAuthLogout},
	CategoryWrite:    {EventUserCreate},
}

// AuthLoginFields describes every field on [EventAuthLogin] events.
type AuthLoginFields struct {
	ActorID    audit.FieldInfo // required
	Method     audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// AuthLoginEvent builds a type-safe audit event: User authenticated successfully.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthLoginEvent struct {
	fields audit.Fields
}

// NewAuthLoginEvent creates a EventAuthLogin event with required fields.
func NewAuthLoginEvent(actorID any, method any, outcome any) *AuthLoginEvent {
	return &AuthLoginEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldMethod:  method,
		FieldOutcome: outcome,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *AuthLoginEvent) SetAction(v any) *AuthLoginEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *AuthLoginEvent) SetActorUID(v any) *AuthLoginEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *AuthLoginEvent) SetDestHost(v any) *AuthLoginEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *AuthLoginEvent) SetDestIP(v any) *AuthLoginEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *AuthLoginEvent) SetDestPort(v any) *AuthLoginEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *AuthLoginEvent) SetEndTime(v any) *AuthLoginEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *AuthLoginEvent) SetFileHash(v any) *AuthLoginEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *AuthLoginEvent) SetFileName(v any) *AuthLoginEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *AuthLoginEvent) SetFilePath(v any) *AuthLoginEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *AuthLoginEvent) SetFileSize(v any) *AuthLoginEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *AuthLoginEvent) SetMessage(v any) *AuthLoginEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *AuthLoginEvent) SetPath(v any) *AuthLoginEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *AuthLoginEvent) SetProtocol(v any) *AuthLoginEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *AuthLoginEvent) SetReason(v any) *AuthLoginEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *AuthLoginEvent) SetReferrer(v any) *AuthLoginEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *AuthLoginEvent) SetRequestID(v any) *AuthLoginEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *AuthLoginEvent) SetRole(v any) *AuthLoginEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *AuthLoginEvent) SetSessionID(v any) *AuthLoginEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *AuthLoginEvent) SetSourceHost(v any) *AuthLoginEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *AuthLoginEvent) SetSourceIP(v any) *AuthLoginEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *AuthLoginEvent) SetSourcePort(v any) *AuthLoginEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *AuthLoginEvent) SetStartTime(v any) *AuthLoginEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *AuthLoginEvent) SetTargetID(v any) *AuthLoginEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *AuthLoginEvent) SetTargetRole(v any) *AuthLoginEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *AuthLoginEvent) SetTargetType(v any) *AuthLoginEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *AuthLoginEvent) SetTargetUID(v any) *AuthLoginEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *AuthLoginEvent) SetTransport(v any) *AuthLoginEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *AuthLoginEvent) SetUserAgent(v any) *AuthLoginEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *AuthLoginEvent) EventType() string { return EventAuthLogin }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthLoginEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthLoginEvent) Description() string { return "User authenticated successfully" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthLoginEvent) FieldInfo() AuthLoginFields {
	return AuthLoginFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Method:     audit.FieldInfo{Name: FieldMethod, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthLoginEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// AuthLogoutFields describes every field on [EventAuthLogout] events.
type AuthLogoutFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// AuthLogoutEvent builds a type-safe audit event: User ended their session.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthLogoutEvent struct {
	fields audit.Fields
}

// NewAuthLogoutEvent creates a EventAuthLogout event with required fields.
func NewAuthLogoutEvent(actorID any, outcome any) *AuthLogoutEvent {
	return &AuthLogoutEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *AuthLogoutEvent) SetAction(v any) *AuthLogoutEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *AuthLogoutEvent) SetActorUID(v any) *AuthLogoutEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *AuthLogoutEvent) SetDestHost(v any) *AuthLogoutEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *AuthLogoutEvent) SetDestIP(v any) *AuthLogoutEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *AuthLogoutEvent) SetDestPort(v any) *AuthLogoutEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *AuthLogoutEvent) SetEndTime(v any) *AuthLogoutEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *AuthLogoutEvent) SetFileHash(v any) *AuthLogoutEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *AuthLogoutEvent) SetFileName(v any) *AuthLogoutEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *AuthLogoutEvent) SetFilePath(v any) *AuthLogoutEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *AuthLogoutEvent) SetFileSize(v any) *AuthLogoutEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *AuthLogoutEvent) SetMessage(v any) *AuthLogoutEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *AuthLogoutEvent) SetMethod(v any) *AuthLogoutEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *AuthLogoutEvent) SetPath(v any) *AuthLogoutEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *AuthLogoutEvent) SetProtocol(v any) *AuthLogoutEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *AuthLogoutEvent) SetReason(v any) *AuthLogoutEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *AuthLogoutEvent) SetReferrer(v any) *AuthLogoutEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *AuthLogoutEvent) SetRequestID(v any) *AuthLogoutEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *AuthLogoutEvent) SetRole(v any) *AuthLogoutEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *AuthLogoutEvent) SetSessionID(v any) *AuthLogoutEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *AuthLogoutEvent) SetSourceHost(v any) *AuthLogoutEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *AuthLogoutEvent) SetSourceIP(v any) *AuthLogoutEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *AuthLogoutEvent) SetSourcePort(v any) *AuthLogoutEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *AuthLogoutEvent) SetStartTime(v any) *AuthLogoutEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *AuthLogoutEvent) SetTargetID(v any) *AuthLogoutEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *AuthLogoutEvent) SetTargetRole(v any) *AuthLogoutEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *AuthLogoutEvent) SetTargetType(v any) *AuthLogoutEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *AuthLogoutEvent) SetTargetUID(v any) *AuthLogoutEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *AuthLogoutEvent) SetTransport(v any) *AuthLogoutEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *AuthLogoutEvent) SetUserAgent(v any) *AuthLogoutEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *AuthLogoutEvent) EventType() string { return EventAuthLogout }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthLogoutEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthLogoutEvent) Description() string { return "User ended their session" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthLogoutEvent) FieldInfo() AuthLogoutFields {
	return AuthLogoutFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthLogoutEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	TargetID   audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any, targetID any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldOutcome:  outcome,
		FieldTargetID: targetID,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *UserCreateEvent) SetAction(v any) *UserCreateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserCreateEvent) SetActorUID(v any) *UserCreateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserCreateEvent) SetDestHost(v any) *UserCreateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserCreateEvent) SetDestIP(v any) *UserCreateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserCreateEvent) SetDestPort(v any) *UserCreateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserCreateEvent) SetEndTime(v any) *UserCreateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserCreateEvent) SetFileHash(v any) *UserCreateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserCreateEvent) SetFileName(v any) *UserCreateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserCreateEvent) SetFilePath(v any) *UserCreateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserCreateEvent) SetFileSize(v any) *UserCreateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserCreateEvent) SetMessage(v any) *UserCreateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserCreateEvent) SetMethod(v any) *UserCreateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserCreateEvent) SetPath(v any) *UserCreateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserCreateEvent) SetProtocol(v any) *UserCreateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserCreateEvent) SetReason(v any) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserCreateEvent) SetReferrer(v any) *UserCreateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserCreateEvent) SetRequestID(v any) *UserCreateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserCreateEvent) SetRole(v any) *UserCreateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserCreateEvent) SetSessionID(v any) *UserCreateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserCreateEvent) SetSourceHost(v any) *UserCreateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserCreateEvent) SetSourceIP(v any) *UserCreateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserCreateEvent) SetSourcePort(v any) *UserCreateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserCreateEvent) SetStartTime(v any) *UserCreateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserCreateEvent) SetTargetRole(v any) *UserCreateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserCreateEvent) SetTargetType(v any) *UserCreateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserCreateEvent) SetTargetUID(v any) *UserCreateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserCreateEvent) SetTransport(v any) *UserCreateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserCreateEvent) SetUserAgent(v any) *UserCreateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID:   audit.FieldInfo{Name: FieldTargetID, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}
