// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryLifecycle = "lifecycle"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventShutdown: {
		Required: []string{FieldAppName},
		Optional: []string{FieldReason, FieldUptimeMS},
	},
	EventStartup: {
		Required: []string{FieldAppName},
		Optional: []string{FieldConfig, FieldVersion},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryLifecycle: {EventShutdown, EventStartup},
	CategorySecurity:  {EventAuthFailure},
	CategoryWrite:     {EventUserCreate},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// AuthFailureEvent builds a type-safe audit event: An authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "An authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// ShutdownFields describes every field on [EventShutdown] events.
type ShutdownFields struct {
	AppName  audit.FieldInfo // required
	Reason   audit.FieldInfo // optional
	UptimeMS audit.FieldInfo // optional
}

// ShutdownEvent builds a type-safe audit event: Application shutting down.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ShutdownEvent struct {
	fields audit.Fields
}

// NewShutdownEvent creates a EventShutdown event with required fields.
func NewShutdownEvent(appName any) *ShutdownEvent {
	return &ShutdownEvent{fields: audit.Fields{
		FieldAppName: appName,
	}}
}

// SetReason sets the FieldReason field.
func (e *ShutdownEvent) SetReason(v any) *ShutdownEvent {
	e.fields[FieldReason] = v
	return e
}

// SetUptimeMS sets the FieldUptimeMS field.
func (e *ShutdownEvent) SetUptimeMS(v any) *ShutdownEvent {
	e.fields[FieldUptimeMS] = v
	return e
}

// EventType returns the event type name.
func (e *ShutdownEvent) EventType() string { return EventShutdown }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ShutdownEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ShutdownEvent) Description() string { return "Application shutting down" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ShutdownEvent) FieldInfo() ShutdownFields {
	return ShutdownFields{
		AppName:  audit.FieldInfo{Name: FieldAppName, Required: true},
		Reason:   audit.FieldInfo{Name: FieldReason},
		UptimeMS: audit.FieldInfo{Name: FieldUptimeMS},
	}
}

// Categories returns the categories this event belongs to.
func (e *ShutdownEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryLifecycle},
	}
}

// StartupFields describes every field on [EventStartup] events.
type StartupFields struct {
	AppName audit.FieldInfo // required
	Config  audit.FieldInfo // optional
	Version audit.FieldInfo // optional
}

// StartupEvent builds a type-safe audit event: Application started.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type StartupEvent struct {
	fields audit.Fields
}

// NewStartupEvent creates a EventStartup event with required fields.
func NewStartupEvent(appName any) *StartupEvent {
	return &StartupEvent{fields: audit.Fields{
		FieldAppName: appName,
	}}
}

// SetConfig sets the FieldConfig field.
func (e *StartupEvent) SetConfig(v any) *StartupEvent {
	e.fields[FieldConfig] = v
	return e
}

// SetVersion sets the FieldVersion field.
func (e *StartupEvent) SetVersion(v any) *StartupEvent {
	e.fields[FieldVersion] = v
	return e
}

// EventType returns the event type name.
func (e *StartupEvent) EventType() string { return EventStartup }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *StartupEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *StartupEvent) Description() string { return "Application started" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *StartupEvent) FieldInfo() StartupFields {
	return StartupFields{
		AppName: audit.FieldInfo{Name: FieldAppName, Required: true},
		Config:  audit.FieldInfo{Name: FieldConfig},
		Version: audit.FieldInfo{Name: FieldVersion},
	}
}

// Categories returns the categories this event belongs to.
func (e *StartupEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryLifecycle},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}
