// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventPaymentProcess — A payment was processed
	EventPaymentProcess = "payment_process"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryWrite = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID    = "actor_id"
	FieldAmount     = "amount"
	FieldCardExpiry = "card_expiry"
	FieldCardNumber = "card_number"
	FieldDepartment = "department"
	FieldEmail      = "email"
	FieldOutcome    = "outcome"
	FieldPhone      = "phone"
	FieldUserName   = "user_name"
)

// Sensitivity label constants — use with exclude_labels
// in output configuration.
const (
	// LabelFinancial — Financial and payment data
	LabelFinancial = "financial"
	// LabelPii — Personally identifiable information
	LabelPii = "pii"
)

// FieldLabels maps field names to the sensitivity labels they carry.
// Resolved from all three mechanisms: explicit annotation, global
// field mapping, and regex patterns.
var FieldLabels = map[string][]string{
	FieldCardExpiry: {LabelFinancial},
	FieldCardNumber: {LabelFinancial},
	FieldEmail:      {LabelPii},
	FieldPhone:      {LabelPii},
	FieldUserName:   {LabelPii},
}

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventPaymentProcess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldAmount, FieldCardExpiry, FieldCardNumber},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldDepartment, FieldEmail, FieldPhone, FieldUserName},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryWrite: {EventPaymentProcess, EventUserCreate},
}

// PaymentProcessFields describes every field on [EventPaymentProcess] events.
type PaymentProcessFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Amount     audit.FieldInfo // optional
	CardExpiry audit.FieldInfo // optional
	CardNumber audit.FieldInfo // optional
}

// PaymentProcessEvent builds a type-safe audit event: A payment was processed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type PaymentProcessEvent struct {
	fields audit.Fields
}

// NewPaymentProcessEvent creates a EventPaymentProcess event with required fields.
func NewPaymentProcessEvent(actorID any, outcome any) *PaymentProcessEvent {
	return &PaymentProcessEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetAmount sets the FieldAmount field.
func (e *PaymentProcessEvent) SetAmount(v any) *PaymentProcessEvent {
	e.fields[FieldAmount] = v
	return e
}

// SetCardExpiry sets the FieldCardExpiry field.
// Sensitivity label: LabelFinancial — Financial and payment data
func (e *PaymentProcessEvent) SetCardExpiry(v any) *PaymentProcessEvent {
	e.fields[FieldCardExpiry] = v
	return e
}

// SetCardNumber sets the FieldCardNumber field.
// Sensitivity label: LabelFinancial — Financial and payment data
func (e *PaymentProcessEvent) SetCardNumber(v any) *PaymentProcessEvent {
	e.fields[FieldCardNumber] = v
	return e
}

// EventType returns the event type name.
func (e *PaymentProcessEvent) EventType() string { return EventPaymentProcess }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *PaymentProcessEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *PaymentProcessEvent) Description() string { return "A payment was processed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *PaymentProcessEvent) FieldInfo() PaymentProcessFields {
	return PaymentProcessFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Amount:     audit.FieldInfo{Name: FieldAmount},
		CardExpiry: audit.FieldInfo{Name: FieldCardExpiry, Labels: []audit.LabelInfo{{Name: LabelFinancial, Description: "Financial and payment data"}}},
		CardNumber: audit.FieldInfo{Name: FieldCardNumber, Labels: []audit.LabelInfo{{Name: LabelFinancial, Description: "Financial and payment data"}}},
	}
}

// Categories returns the categories this event belongs to.
func (e *PaymentProcessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Department audit.FieldInfo // optional
	Email      audit.FieldInfo // optional
	Phone      audit.FieldInfo // optional
	UserName   audit.FieldInfo // optional
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetDepartment sets the FieldDepartment field.
func (e *UserCreateEvent) SetDepartment(v any) *UserCreateEvent {
	e.fields[FieldDepartment] = v
	return e
}

// SetEmail sets the FieldEmail field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetEmail(v any) *UserCreateEvent {
	e.fields[FieldEmail] = v
	return e
}

// SetPhone sets the FieldPhone field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetPhone(v any) *UserCreateEvent {
	e.fields[FieldPhone] = v
	return e
}

// SetUserName sets the FieldUserName field.
// Sensitivity label: LabelPii — Personally identifiable information
func (e *UserCreateEvent) SetUserName(v any) *UserCreateEvent {
	e.fields[FieldUserName] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Department: audit.FieldInfo{Name: FieldDepartment},
		Email:      audit.FieldInfo{Name: FieldEmail, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
		Phone:      audit.FieldInfo{Name: FieldPhone, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
		UserName:   audit.FieldInfo{Name: FieldUserName, Labels: []audit.LabelInfo{{Name: LabelPii, Description: "Personally identifiable information"}}},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}
