// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID = "actor_id"
	FieldEmail   = "email"
	FieldOutcome = "outcome"
	FieldReason  = "reason"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldEmail},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategorySecurity: {EventAuthFailure},
	CategoryWrite:    {EventUserCreate},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
	Reason  audit.FieldInfo // optional
}

// AuthFailureEvent builds a type-safe audit event: An authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetReason sets the FieldReason field.
func (e *AuthFailureEvent) SetReason(v any) *AuthFailureEvent {
	e.fields[FieldReason] = v
	return e
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "An authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:  audit.FieldInfo{Name: FieldReason},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity, Severity: intPtr(8)},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
	Email   audit.FieldInfo // optional
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetEmail sets the FieldEmail field.
func (e *UserCreateEvent) SetEmail(v any) *UserCreateEvent {
	e.fields[FieldEmail] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
		Email:   audit.FieldInfo{Name: FieldEmail},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

func intPtr(n int) *int { return &n }
