// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventConfigChange — A configuration change was made
	EventConfigChange = "config_change"
	// EventItemCreate — An item was created
	EventItemCreate = "item_create"
	// EventItemDelete — An item was deleted
	EventItemDelete = "item_delete"
	// EventItemList — Items were listed
	EventItemList = "item_list"
	// EventItemRead — An item was read
	EventItemRead = "item_read"
	// EventItemUpdate — An item was updated
	EventItemUpdate = "item_update"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryAdmin    = "admin"
	CategoryRead     = "read"
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldSourceIP = "source_ip"
	FieldTargetID = "target_id"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldSourceIP},
	},
	EventAuthSuccess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldSourceIP},
	},
	EventConfigChange: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemDelete: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemList: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID},
	},
	EventItemRead: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID, FieldTargetID},
	},
	EventItemUpdate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryAdmin:    {EventConfigChange},
	CategoryRead:     {EventItemList, EventItemRead},
	CategorySecurity: {EventAuthFailure, EventAuthSuccess},
	CategoryWrite:    {EventItemCreate, EventItemDelete, EventItemUpdate},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	Reason   audit.FieldInfo // optional
	SourceIP audit.FieldInfo // optional
}

// AuthFailureEvent builds a type-safe audit event: An authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetReason sets the FieldReason field.
func (e *AuthFailureEvent) SetReason(v any) *AuthFailureEvent {
	e.fields[FieldReason] = v
	return e
}

// SetSourceIP sets the FieldSourceIP field.
func (e *AuthFailureEvent) SetSourceIP(v any) *AuthFailureEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "An authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:   audit.FieldInfo{Name: FieldReason},
		SourceIP: audit.FieldInfo{Name: FieldSourceIP},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity, Severity: intPtr(8)},
	}
}

// AuthSuccessFields describes every field on [EventAuthSuccess] events.
type AuthSuccessFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	SourceIP audit.FieldInfo // optional
}

// AuthSuccessEvent builds a type-safe audit event: An authentication attempt succeeded.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthSuccessEvent struct {
	fields audit.Fields
}

// NewAuthSuccessEvent creates a EventAuthSuccess event with required fields.
func NewAuthSuccessEvent(actorID any, outcome any) *AuthSuccessEvent {
	return &AuthSuccessEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetSourceIP sets the FieldSourceIP field.
func (e *AuthSuccessEvent) SetSourceIP(v any) *AuthSuccessEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// EventType returns the event type name.
func (e *AuthSuccessEvent) EventType() string { return EventAuthSuccess }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthSuccessEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthSuccessEvent) Description() string { return "An authentication attempt succeeded" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthSuccessEvent) FieldInfo() AuthSuccessFields {
	return AuthSuccessFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		SourceIP: audit.FieldInfo{Name: FieldSourceIP},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthSuccessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity, Severity: intPtr(8)},
	}
}

// ConfigChangeFields describes every field on [EventConfigChange] events.
type ConfigChangeFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	TargetID audit.FieldInfo // optional
}

// ConfigChangeEvent builds a type-safe audit event: A configuration change was made.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ConfigChangeEvent struct {
	fields audit.Fields
}

// NewConfigChangeEvent creates a EventConfigChange event with required fields.
func NewConfigChangeEvent(actorID any, outcome any) *ConfigChangeEvent {
	return &ConfigChangeEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetTargetID sets the FieldTargetID field.
func (e *ConfigChangeEvent) SetTargetID(v any) *ConfigChangeEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *ConfigChangeEvent) EventType() string { return EventConfigChange }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ConfigChangeEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ConfigChangeEvent) Description() string { return "A configuration change was made" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ConfigChangeEvent) FieldInfo() ConfigChangeFields {
	return ConfigChangeFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ConfigChangeEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryAdmin, Severity: intPtr(6)},
	}
}

// ItemCreateFields describes every field on [EventItemCreate] events.
type ItemCreateFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	TargetID audit.FieldInfo // optional
}

// ItemCreateEvent builds a type-safe audit event: An item was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ItemCreateEvent struct {
	fields audit.Fields
}

// NewItemCreateEvent creates a EventItemCreate event with required fields.
func NewItemCreateEvent(actorID any, outcome any) *ItemCreateEvent {
	return &ItemCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetTargetID sets the FieldTargetID field.
func (e *ItemCreateEvent) SetTargetID(v any) *ItemCreateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *ItemCreateEvent) EventType() string { return EventItemCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ItemCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ItemCreateEvent) Description() string { return "An item was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ItemCreateEvent) FieldInfo() ItemCreateFields {
	return ItemCreateFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ItemCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite, Severity: intPtr(4)},
	}
}

// ItemDeleteFields describes every field on [EventItemDelete] events.
type ItemDeleteFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	TargetID audit.FieldInfo // optional
}

// ItemDeleteEvent builds a type-safe audit event: An item was deleted.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ItemDeleteEvent struct {
	fields audit.Fields
}

// NewItemDeleteEvent creates a EventItemDelete event with required fields.
func NewItemDeleteEvent(actorID any, outcome any) *ItemDeleteEvent {
	return &ItemDeleteEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetTargetID sets the FieldTargetID field.
func (e *ItemDeleteEvent) SetTargetID(v any) *ItemDeleteEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *ItemDeleteEvent) EventType() string { return EventItemDelete }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ItemDeleteEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ItemDeleteEvent) Description() string { return "An item was deleted" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ItemDeleteEvent) FieldInfo() ItemDeleteFields {
	return ItemDeleteFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ItemDeleteEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite, Severity: intPtr(4)},
	}
}

// ItemListFields describes every field on [EventItemList] events.
type ItemListFields struct {
	Outcome audit.FieldInfo // required
	ActorID audit.FieldInfo // optional
}

// ItemListEvent builds a type-safe audit event: Items were listed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ItemListEvent struct {
	fields audit.Fields
}

// NewItemListEvent creates a EventItemList event with required fields.
func NewItemListEvent(outcome any) *ItemListEvent {
	return &ItemListEvent{fields: audit.Fields{
		FieldOutcome: outcome,
	}}
}

// SetActorID sets the FieldActorID field.
func (e *ItemListEvent) SetActorID(v any) *ItemListEvent {
	e.fields[FieldActorID] = v
	return e
}

// EventType returns the event type name.
func (e *ItemListEvent) EventType() string { return EventItemList }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ItemListEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ItemListEvent) Description() string { return "Items were listed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ItemListEvent) FieldInfo() ItemListFields {
	return ItemListFields{
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
		ActorID: audit.FieldInfo{Name: FieldActorID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ItemListEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryRead, Severity: intPtr(2)},
	}
}

// ItemReadFields describes every field on [EventItemRead] events.
type ItemReadFields struct {
	Outcome  audit.FieldInfo // required
	ActorID  audit.FieldInfo // optional
	TargetID audit.FieldInfo // optional
}

// ItemReadEvent builds a type-safe audit event: An item was read.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ItemReadEvent struct {
	fields audit.Fields
}

// NewItemReadEvent creates a EventItemRead event with required fields.
func NewItemReadEvent(outcome any) *ItemReadEvent {
	return &ItemReadEvent{fields: audit.Fields{
		FieldOutcome: outcome,
	}}
}

// SetActorID sets the FieldActorID field.
func (e *ItemReadEvent) SetActorID(v any) *ItemReadEvent {
	e.fields[FieldActorID] = v
	return e
}

// SetTargetID sets the FieldTargetID field.
func (e *ItemReadEvent) SetTargetID(v any) *ItemReadEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *ItemReadEvent) EventType() string { return EventItemRead }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ItemReadEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ItemReadEvent) Description() string { return "An item was read" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ItemReadEvent) FieldInfo() ItemReadFields {
	return ItemReadFields{
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		ActorID:  audit.FieldInfo{Name: FieldActorID},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ItemReadEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryRead, Severity: intPtr(2)},
	}
}

// ItemUpdateFields describes every field on [EventItemUpdate] events.
type ItemUpdateFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	TargetID audit.FieldInfo // optional
}

// ItemUpdateEvent builds a type-safe audit event: An item was updated.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ItemUpdateEvent struct {
	fields audit.Fields
}

// NewItemUpdateEvent creates a EventItemUpdate event with required fields.
func NewItemUpdateEvent(actorID any, outcome any) *ItemUpdateEvent {
	return &ItemUpdateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetTargetID sets the FieldTargetID field.
func (e *ItemUpdateEvent) SetTargetID(v any) *ItemUpdateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *ItemUpdateEvent) EventType() string { return EventItemUpdate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ItemUpdateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ItemUpdateEvent) Description() string { return "An item was updated" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ItemUpdateEvent) FieldInfo() ItemUpdateFields {
	return ItemUpdateFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *ItemUpdateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite, Severity: intPtr(4)},
	}
}

func intPtr(n int) *int { return &n }
