// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

package main

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
	// EventUserDelete — A user account was deleted
	EventUserDelete = "user_delete"
	// EventUserRead — A user profile was viewed
	EventUserRead = "user_read"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryLifecycle = "lifecycle"
	CategoryRead      = "read"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldSourceIP = "source_ip"
	FieldTargetID = "target_id"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldSourceIP},
	},
	EventAuthSuccess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldSourceIP},
	},
	EventShutdown: {
		Required: []string{FieldAppName},
		Optional: []string{FieldReason, FieldUptimeMS},
	},
	EventStartup: {
		Required: []string{FieldAppName},
		Optional: []string{FieldConfig, FieldVersion},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldTargetID},
	},
	EventUserDelete: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventUserRead: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryLifecycle: {EventShutdown, EventStartup},
	CategoryRead:      {EventUserRead},
	CategorySecurity:  {EventAuthFailure, EventAuthSuccess},
	CategoryWrite:     {EventUserCreate, EventUserDelete},
}
