// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package steps

import (
	"fmt"
	"strconv"
	"time"

	"github.com/cucumber/godog"

	"github.com/axonops/audit"
	"github.com/axonops/audit/tests/bdd/steps/genfixture"
)

// registerTypedBuilderSteps wires step definitions that exercise the
// typed event builders generated by audit-gen for the BDD fixture
// taxonomy at tests/bdd/steps/genfixture/. Each step is intentionally
// thin — it constructs a typed builder and hands it to AuditEvent so
// every scenario verifies the constructor + setter chain end-to-end.
//
// The fixture taxonomy must be loaded first via "Given the typed-builder
// fixture taxonomy" so the auditor accepts the same event types the
// generated builders emit. Length is the registration-table size, not
// branching depth.
//
//nolint:gocognit,gocyclo,cyclop // independent ctx.Step registrations.
func registerTypedBuilderSteps(ctx *godog.ScenarioContext, tc *AuditTestContext) {
	ctx.Step(`^the typed-builder fixture taxonomy$`, func() error {
		tax, err := audit.ParseTaxonomyYAML(genfixture.TaxonomyYAML())
		if err != nil {
			return fmt.Errorf("parse fixture taxonomy: %w", err)
		}
		tc.Taxonomy = tax
		return nil
	})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)"$`,
		func(actorID, outcome string) error {
			evt := genfixture.NewUserCreateEvent(actorID, outcome)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)" and marker "([^"]*)"$`,
		func(actorID, outcome, marker string) error {
			evt := genfixture.NewUserCreateEvent(actorID, outcome).SetMarker(marker)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)" and source_ip "([^"]*)"$`,
		func(actorID, outcome, sourceIP string) error {
			evt := genfixture.NewUserCreateEvent(actorID, outcome).SetSourceIP(sourceIP)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)" and session_count (\d+)$`,
		func(actorID, outcome, count string) error {
			n, parseErr := strconv.Atoi(count)
			if parseErr != nil {
				return fmt.Errorf("parse session_count: %w", parseErr)
			}
			evt := genfixture.NewUserCreateEvent(actorID, outcome).SetSessionCount(n)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)" and retry_after "([^"]*)"$`,
		func(actorID, outcome, dur string) error {
			d, parseErr := time.ParseDuration(dur)
			if parseErr != nil {
				return fmt.Errorf("parse retry_after: %w", parseErr)
			}
			evt := genfixture.NewUserCreateEvent(actorID, outcome).SetRetryAfter(d)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed user_create event with actor_id "([^"]*)" and outcome "([^"]*)" and start_time "([^"]*)"$`,
		func(actorID, outcome, ts string) error {
			t, parseErr := time.Parse(time.RFC3339, ts)
			if parseErr != nil {
				return fmt.Errorf("parse start_time: %w", parseErr)
			}
			evt := genfixture.NewUserCreateEvent(actorID, outcome).SetStartTime(t)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^I audit a typed auth_failure event with actor_id "([^"]*)" and outcome "([^"]*)"$`,
		func(actorID, outcome string) error {
			evt := genfixture.NewAuthFailureEvent(actorID, outcome)
			tc.LastErr = tc.Auditor.AuditEvent(evt)
			return nil
		})

	ctx.Step(`^the typed user_create builder reports description "([^"]*)"$`,
		func(want string) error {
			evt := genfixture.NewUserCreateEvent("alice", "success")
			if got := evt.Description(); got != want {
				return fmt.Errorf("expected description %q, got %q", want, got)
			}
			return nil
		})

	ctx.Step(`^the typed user_create builder reports category "([^"]*)" with severity (\d+)$`,
		func(name, sev string) error {
			wantSev, parseErr := strconv.Atoi(sev)
			if parseErr != nil {
				return fmt.Errorf("parse severity: %w", parseErr)
			}
			evt := genfixture.NewUserCreateEvent("alice", "success")
			cats := evt.Categories()
			for _, c := range cats {
				if c.Name == name {
					if c.Severity == nil {
						return fmt.Errorf("category %q has no severity, expected %d", name, wantSev)
					}
					if *c.Severity != wantSev {
						return fmt.Errorf("category %q severity = %d, expected %d", name, *c.Severity, wantSev)
					}
					return nil
				}
			}
			return fmt.Errorf("category %q not in builder Categories(): %+v", name, cats)
		})

	ctx.Step(`^the typed user_create builder FieldInfoMap has field "([^"]*)" required "([^"]*)"$`,
		func(field, requiredStr string) error {
			wantRequired, parseErr := strconv.ParseBool(requiredStr)
			if parseErr != nil {
				return fmt.Errorf("parse required: %w", parseErr)
			}
			evt := genfixture.NewUserCreateEvent("alice", "success")
			info, ok := evt.FieldInfoMap()[field]
			if !ok {
				return fmt.Errorf("field %q not in FieldInfoMap", field)
			}
			if info.Required != wantRequired {
				return fmt.Errorf("field %q required = %t, expected %t",
					field, info.Required, wantRequired)
			}
			return nil
		})
}
