// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
	// EventUserDelete — A user account was deleted
	EventUserDelete = "user_delete"
	// EventUserRead — A user profile was viewed
	EventUserRead = "user_read"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryLifecycle = "lifecycle"
	CategoryRead      = "read"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldSourceIP = "source_ip"
	FieldTargetID = "target_id"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldSourceIP},
	},
	EventAuthSuccess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldSourceIP},
	},
	EventShutdown: {
		Required: []string{FieldAppName},
		Optional: []string{FieldReason, FieldUptimeMS},
	},
	EventStartup: {
		Required: []string{FieldAppName},
		Optional: []string{FieldConfig, FieldVersion},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldTargetID},
	},
	EventUserDelete: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventUserRead: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryLifecycle: {EventShutdown, EventStartup},
	CategoryRead:      {EventUserRead},
	CategorySecurity:  {EventAuthFailure, EventAuthSuccess},
	CategoryWrite:     {EventUserCreate, EventUserDelete},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	Reason   audit.FieldInfo // optional
	SourceIP audit.FieldInfo // optional
}

// AuthFailureEvent builds a type-safe audit event: An authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetReason sets the FieldReason field.
func (e *AuthFailureEvent) SetReason(v any) *AuthFailureEvent {
	e.fields[FieldReason] = v
	return e
}

// SetSourceIP sets the FieldSourceIP field.
func (e *AuthFailureEvent) SetSourceIP(v any) *AuthFailureEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "An authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:   audit.FieldInfo{Name: FieldReason},
		SourceIP: audit.FieldInfo{Name: FieldSourceIP},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// AuthSuccessFields describes every field on [EventAuthSuccess] events.
type AuthSuccessFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	SourceIP audit.FieldInfo // optional
}

// AuthSuccessEvent builds a type-safe audit event: An authentication attempt succeeded.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthSuccessEvent struct {
	fields audit.Fields
}

// NewAuthSuccessEvent creates a EventAuthSuccess event with required fields.
func NewAuthSuccessEvent(actorID any, outcome any) *AuthSuccessEvent {
	return &AuthSuccessEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetSourceIP sets the FieldSourceIP field.
func (e *AuthSuccessEvent) SetSourceIP(v any) *AuthSuccessEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// EventType returns the event type name.
func (e *AuthSuccessEvent) EventType() string { return EventAuthSuccess }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthSuccessEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthSuccessEvent) Description() string { return "An authentication attempt succeeded" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthSuccessEvent) FieldInfo() AuthSuccessFields {
	return AuthSuccessFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		SourceIP: audit.FieldInfo{Name: FieldSourceIP},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthSuccessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// ShutdownFields describes every field on [EventShutdown] events.
type ShutdownFields struct {
	AppName  audit.FieldInfo // required
	Reason   audit.FieldInfo // optional
	UptimeMS audit.FieldInfo // optional
}

// ShutdownEvent builds a type-safe audit event: Application shutting down.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ShutdownEvent struct {
	fields audit.Fields
}

// NewShutdownEvent creates a EventShutdown event with required fields.
func NewShutdownEvent(appName any) *ShutdownEvent {
	return &ShutdownEvent{fields: audit.Fields{
		FieldAppName: appName,
	}}
}

// SetReason sets the FieldReason field.
func (e *ShutdownEvent) SetReason(v any) *ShutdownEvent {
	e.fields[FieldReason] = v
	return e
}

// SetUptimeMS sets the FieldUptimeMS field.
func (e *ShutdownEvent) SetUptimeMS(v any) *ShutdownEvent {
	e.fields[FieldUptimeMS] = v
	return e
}

// EventType returns the event type name.
func (e *ShutdownEvent) EventType() string { return EventShutdown }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ShutdownEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ShutdownEvent) Description() string { return "Application shutting down" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ShutdownEvent) FieldInfo() ShutdownFields {
	return ShutdownFields{
		AppName:  audit.FieldInfo{Name: FieldAppName, Required: true},
		Reason:   audit.FieldInfo{Name: FieldReason},
		UptimeMS: audit.FieldInfo{Name: FieldUptimeMS},
	}
}

// Categories returns the categories this event belongs to.
func (e *ShutdownEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryLifecycle},
	}
}

// StartupFields describes every field on [EventStartup] events.
type StartupFields struct {
	AppName audit.FieldInfo // required
	Config  audit.FieldInfo // optional
	Version audit.FieldInfo // optional
}

// StartupEvent builds a type-safe audit event: Application started.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type StartupEvent struct {
	fields audit.Fields
}

// NewStartupEvent creates a EventStartup event with required fields.
func NewStartupEvent(appName any) *StartupEvent {
	return &StartupEvent{fields: audit.Fields{
		FieldAppName: appName,
	}}
}

// SetConfig sets the FieldConfig field.
func (e *StartupEvent) SetConfig(v any) *StartupEvent {
	e.fields[FieldConfig] = v
	return e
}

// SetVersion sets the FieldVersion field.
func (e *StartupEvent) SetVersion(v any) *StartupEvent {
	e.fields[FieldVersion] = v
	return e
}

// EventType returns the event type name.
func (e *StartupEvent) EventType() string { return EventStartup }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *StartupEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *StartupEvent) Description() string { return "Application started" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *StartupEvent) FieldInfo() StartupFields {
	return StartupFields{
		AppName: audit.FieldInfo{Name: FieldAppName, Required: true},
		Config:  audit.FieldInfo{Name: FieldConfig},
		Version: audit.FieldInfo{Name: FieldVersion},
	}
}

// Categories returns the categories this event belongs to.
func (e *StartupEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryLifecycle},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	Reason   audit.FieldInfo // optional
	TargetID audit.FieldInfo // optional
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetReason sets the FieldReason field.
func (e *UserCreateEvent) SetReason(v any) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetTargetID sets the FieldTargetID field.
func (e *UserCreateEvent) SetTargetID(v any) *UserCreateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:   audit.FieldInfo{Name: FieldReason},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserDeleteFields describes every field on [EventUserDelete] events.
type UserDeleteFields struct {
	ActorID  audit.FieldInfo // required
	Outcome  audit.FieldInfo // required
	TargetID audit.FieldInfo // optional
}

// UserDeleteEvent builds a type-safe audit event: A user account was deleted.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserDeleteEvent struct {
	fields audit.Fields
}

// NewUserDeleteEvent creates a EventUserDelete event with required fields.
func NewUserDeleteEvent(actorID any, outcome any) *UserDeleteEvent {
	return &UserDeleteEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetTargetID sets the FieldTargetID field.
func (e *UserDeleteEvent) SetTargetID(v any) *UserDeleteEvent {
	e.fields[FieldTargetID] = v
	return e
}

// EventType returns the event type name.
func (e *UserDeleteEvent) EventType() string { return EventUserDelete }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserDeleteEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserDeleteEvent) Description() string { return "A user account was deleted" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserDeleteEvent) FieldInfo() UserDeleteFields {
	return UserDeleteFields{
		ActorID:  audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:  audit.FieldInfo{Name: FieldOutcome, Required: true},
		TargetID: audit.FieldInfo{Name: FieldTargetID},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserDeleteEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserReadFields describes every field on [EventUserRead] events.
type UserReadFields struct {
	Outcome audit.FieldInfo // required
	ActorID audit.FieldInfo // optional
}

// UserReadEvent builds a type-safe audit event: A user profile was viewed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserReadEvent struct {
	fields audit.Fields
}

// NewUserReadEvent creates a EventUserRead event with required fields.
func NewUserReadEvent(outcome any) *UserReadEvent {
	return &UserReadEvent{fields: audit.Fields{
		FieldOutcome: outcome,
	}}
}

// SetActorID sets the FieldActorID field.
func (e *UserReadEvent) SetActorID(v any) *UserReadEvent {
	e.fields[FieldActorID] = v
	return e
}

// EventType returns the event type name.
func (e *UserReadEvent) EventType() string { return EventUserRead }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserReadEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserReadEvent) Description() string { return "A user profile was viewed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserReadEvent) FieldInfo() UserReadFields {
	return UserReadFields{
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
		ActorID: audit.FieldInfo{Name: FieldActorID},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserReadEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryRead},
	}
}
