// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
	// EventUserDelete — A user account was deleted
	EventUserDelete = "user_delete"
	// EventUserRead — A user profile was viewed
	EventUserRead = "user_read"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryRead     = "read"
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID = "actor_id"
	FieldOutcome = "outcome"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventAuthSuccess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventUserDelete: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventUserRead: {
		Required: []string{FieldOutcome},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryRead:     {EventUserRead},
	CategorySecurity: {EventAuthFailure, EventAuthSuccess},
	CategoryWrite:    {EventUserCreate, EventUserDelete},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// AuthFailureEvent builds a type-safe audit event: An authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "An authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// AuthSuccessFields describes every field on [EventAuthSuccess] events.
type AuthSuccessFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// AuthSuccessEvent builds a type-safe audit event: An authentication attempt succeeded.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthSuccessEvent struct {
	fields audit.Fields
}

// NewAuthSuccessEvent creates a EventAuthSuccess event with required fields.
func NewAuthSuccessEvent(actorID any, outcome any) *AuthSuccessEvent {
	return &AuthSuccessEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *AuthSuccessEvent) EventType() string { return EventAuthSuccess }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthSuccessEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthSuccessEvent) Description() string { return "An authentication attempt succeeded" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthSuccessEvent) FieldInfo() AuthSuccessFields {
	return AuthSuccessFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthSuccessEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserDeleteFields describes every field on [EventUserDelete] events.
type UserDeleteFields struct {
	ActorID audit.FieldInfo // required
	Outcome audit.FieldInfo // required
}

// UserDeleteEvent builds a type-safe audit event: A user account was deleted.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserDeleteEvent struct {
	fields audit.Fields
}

// NewUserDeleteEvent creates a EventUserDelete event with required fields.
func NewUserDeleteEvent(actorID any, outcome any) *UserDeleteEvent {
	return &UserDeleteEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *UserDeleteEvent) EventType() string { return EventUserDelete }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserDeleteEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserDeleteEvent) Description() string { return "A user account was deleted" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserDeleteEvent) FieldInfo() UserDeleteFields {
	return UserDeleteFields{
		ActorID: audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserDeleteEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserReadFields describes every field on [EventUserRead] events.
type UserReadFields struct {
	Outcome audit.FieldInfo // required
}

// UserReadEvent builds a type-safe audit event: A user profile was viewed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserReadEvent struct {
	fields audit.Fields
}

// NewUserReadEvent creates a EventUserRead event with required fields.
func NewUserReadEvent(outcome any) *UserReadEvent {
	return &UserReadEvent{fields: audit.Fields{
		FieldOutcome: outcome,
	}}
}

// EventType returns the event type name.
func (e *UserReadEvent) EventType() string { return EventUserRead }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserReadEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserReadEvent) Description() string { return "A user profile was viewed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserReadEvent) FieldInfo() UserReadFields {
	return UserReadFields{
		Outcome: audit.FieldInfo{Name: FieldOutcome, Required: true},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserReadEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryRead},
	}
}
