// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package genfixture provides typed event builders generated by
// audit-gen from the BDD test taxonomy. It exists so the typed-builder
// BDD scenarios in tests/bdd/features/typed_builders.feature can
// exercise the real audit-gen output end-to-end (constructor, setters,
// FieldsDonor donation, Categories, FieldInfoMap).
//
// audit_generated.go is committed to version control. Re-generate by
// running `go generate ./...` from tests/bdd/steps/genfixture.
package genfixture

//go:generate go run github.com/axonops/audit/cmd/audit-gen -input taxonomy.yaml -output audit_generated.go -package genfixture
