// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

package main

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryLifecycle = "lifecycle"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)

// FieldLabels maps field names to the sensitivity labels they carry.
// Resolved from all three mechanisms: explicit annotation, global
// field mapping, and regex patterns.
var FieldLabels = map[string][]string{}

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	"auth_failure": {
		Required: []string{"actor_id", "outcome"},
		Optional: []string(nil),
	},
	"auth_success": {
		Required: []string{"actor_id", "outcome"},
		Optional: []string(nil),
	},
	"shutdown": {
		Required: []string{"app_name"},
		Optional: []string{"reason", "uptime_ms"},
	},
	"startup": {
		Required: []string{"app_name"},
		Optional: []string{"config", "version"},
	},
	"user_create": {
		Required: []string{"actor_id", "outcome"},
		Optional: []string(nil),
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	"lifecycle": {"shutdown", "startup"},
	"security":  {"auth_failure", "auth_success"},
	"write":     {"user_create"},
}
