// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

package main

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventConfigChange — A configuration change was made
	EventConfigChange = "config_change"
	// EventItemCreate — An item was created
	EventItemCreate = "item_create"
	// EventItemDelete — An item was deleted
	EventItemDelete = "item_delete"
	// EventItemList — Items were listed
	EventItemList = "item_list"
	// EventItemRead — An item was read
	EventItemRead = "item_read"
	// EventItemUpdate — An item was updated
	EventItemUpdate = "item_update"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryAdmin     = "admin"
	CategoryLifecycle = "lifecycle"
	CategoryRead      = "read"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldSourceIP = "source_ip"
	FieldTargetID = "target_id"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)
