// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

package main

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — An authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthSuccess — An authentication attempt succeeded
	EventAuthSuccess = "auth_success"
	// EventConfigChange — A configuration change was made
	EventConfigChange = "config_change"
	// EventItemCreate — An item was created
	EventItemCreate = "item_create"
	// EventItemDelete — An item was deleted
	EventItemDelete = "item_delete"
	// EventItemList — Items were listed
	EventItemList = "item_list"
	// EventItemRead — An item was read
	EventItemRead = "item_read"
	// EventItemUpdate — An item was updated
	EventItemUpdate = "item_update"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryAdmin     = "admin"
	CategoryLifecycle = "lifecycle"
	CategoryRead      = "read"
	CategorySecurity  = "security"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID  = "actor_id"
	FieldAppName  = "app_name"
	FieldConfig   = "config"
	FieldOutcome  = "outcome"
	FieldReason   = "reason"
	FieldSourceIP = "source_ip"
	FieldTargetID = "target_id"
	FieldUptimeMS = "uptime_ms"
	FieldVersion  = "version"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldReason, FieldSourceIP},
	},
	EventAuthSuccess: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldSourceIP},
	},
	EventConfigChange: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemDelete: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventItemList: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID},
	},
	EventItemRead: {
		Required: []string{FieldOutcome},
		Optional: []string{FieldActorID, FieldTargetID},
	},
	EventItemUpdate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldTargetID},
	},
	EventShutdown: {
		Required: []string{FieldAppName},
		Optional: []string{FieldReason, FieldUptimeMS},
	},
	EventStartup: {
		Required: []string{FieldAppName},
		Optional: []string{FieldConfig, FieldVersion},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryAdmin:     {EventConfigChange},
	CategoryLifecycle: {EventShutdown, EventStartup},
	CategoryRead:      {EventItemList, EventItemRead},
	CategorySecurity:  {EventAuthFailure, EventAuthSuccess},
	CategoryWrite:     {EventItemCreate, EventItemDelete, EventItemUpdate},
}
