// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import audit "github.com/axonops/go-audit"

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventAuthFailure — Authentication attempt failed
	EventAuthFailure = "auth_failure"
	// EventAuthLogin — User authenticated successfully
	EventAuthLogin = "auth_login"
	// EventConfigChange — System configuration was modified
	EventConfigChange = "config_change"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldNewValue   = "new_value"
	FieldOldValue   = "old_value"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSetting    = "setting"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome, FieldReason},
		Optional: []string{},
	},
	EventAuthLogin: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
	EventConfigChange: {
		Required: []string{FieldActorID, FieldNewValue, FieldOldValue, FieldOutcome, FieldSetting},
		Optional: []string{},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategorySecurity: {EventAuthFailure, EventAuthLogin},
	CategoryWrite:    {EventConfigChange, EventUserCreate},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Reason     audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// AuthFailureEvent builds a type-safe audit event: Authentication attempt failed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID any, outcome any, reason any) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
		FieldReason:  reason,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *AuthFailureEvent) SetAction(v any) *AuthFailureEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *AuthFailureEvent) SetActorUID(v any) *AuthFailureEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *AuthFailureEvent) SetDestHost(v any) *AuthFailureEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *AuthFailureEvent) SetDestIP(v any) *AuthFailureEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *AuthFailureEvent) SetDestPort(v any) *AuthFailureEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *AuthFailureEvent) SetEndTime(v any) *AuthFailureEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *AuthFailureEvent) SetFileHash(v any) *AuthFailureEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *AuthFailureEvent) SetFileName(v any) *AuthFailureEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *AuthFailureEvent) SetFilePath(v any) *AuthFailureEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *AuthFailureEvent) SetFileSize(v any) *AuthFailureEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *AuthFailureEvent) SetMessage(v any) *AuthFailureEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *AuthFailureEvent) SetMethod(v any) *AuthFailureEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *AuthFailureEvent) SetPath(v any) *AuthFailureEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *AuthFailureEvent) SetProtocol(v any) *AuthFailureEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *AuthFailureEvent) SetReferrer(v any) *AuthFailureEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *AuthFailureEvent) SetRequestID(v any) *AuthFailureEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *AuthFailureEvent) SetRole(v any) *AuthFailureEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *AuthFailureEvent) SetSessionID(v any) *AuthFailureEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *AuthFailureEvent) SetSourceHost(v any) *AuthFailureEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *AuthFailureEvent) SetSourceIP(v any) *AuthFailureEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *AuthFailureEvent) SetSourcePort(v any) *AuthFailureEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *AuthFailureEvent) SetStartTime(v any) *AuthFailureEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *AuthFailureEvent) SetTargetID(v any) *AuthFailureEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *AuthFailureEvent) SetTargetRole(v any) *AuthFailureEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *AuthFailureEvent) SetTargetType(v any) *AuthFailureEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *AuthFailureEvent) SetTargetUID(v any) *AuthFailureEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *AuthFailureEvent) SetTransport(v any) *AuthFailureEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *AuthFailureEvent) SetUserAgent(v any) *AuthFailureEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "Authentication attempt failed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:     audit.FieldInfo{Name: FieldReason, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// AuthLoginFields describes every field on [EventAuthLogin] events.
type AuthLoginFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// AuthLoginEvent builds a type-safe audit event: User authenticated successfully.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthLoginEvent struct {
	fields audit.Fields
}

// NewAuthLoginEvent creates a EventAuthLogin event with required fields.
func NewAuthLoginEvent(actorID any, outcome any) *AuthLoginEvent {
	return &AuthLoginEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *AuthLoginEvent) SetAction(v any) *AuthLoginEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *AuthLoginEvent) SetActorUID(v any) *AuthLoginEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *AuthLoginEvent) SetDestHost(v any) *AuthLoginEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *AuthLoginEvent) SetDestIP(v any) *AuthLoginEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *AuthLoginEvent) SetDestPort(v any) *AuthLoginEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *AuthLoginEvent) SetEndTime(v any) *AuthLoginEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *AuthLoginEvent) SetFileHash(v any) *AuthLoginEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *AuthLoginEvent) SetFileName(v any) *AuthLoginEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *AuthLoginEvent) SetFilePath(v any) *AuthLoginEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *AuthLoginEvent) SetFileSize(v any) *AuthLoginEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *AuthLoginEvent) SetMessage(v any) *AuthLoginEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *AuthLoginEvent) SetMethod(v any) *AuthLoginEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *AuthLoginEvent) SetPath(v any) *AuthLoginEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *AuthLoginEvent) SetProtocol(v any) *AuthLoginEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *AuthLoginEvent) SetReason(v any) *AuthLoginEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *AuthLoginEvent) SetReferrer(v any) *AuthLoginEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *AuthLoginEvent) SetRequestID(v any) *AuthLoginEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *AuthLoginEvent) SetRole(v any) *AuthLoginEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *AuthLoginEvent) SetSessionID(v any) *AuthLoginEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *AuthLoginEvent) SetSourceHost(v any) *AuthLoginEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *AuthLoginEvent) SetSourceIP(v any) *AuthLoginEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *AuthLoginEvent) SetSourcePort(v any) *AuthLoginEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *AuthLoginEvent) SetStartTime(v any) *AuthLoginEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *AuthLoginEvent) SetTargetID(v any) *AuthLoginEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *AuthLoginEvent) SetTargetRole(v any) *AuthLoginEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *AuthLoginEvent) SetTargetType(v any) *AuthLoginEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *AuthLoginEvent) SetTargetUID(v any) *AuthLoginEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *AuthLoginEvent) SetTransport(v any) *AuthLoginEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *AuthLoginEvent) SetUserAgent(v any) *AuthLoginEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *AuthLoginEvent) EventType() string { return EventAuthLogin }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *AuthLoginEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *AuthLoginEvent) Description() string { return "User authenticated successfully" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthLoginEvent) FieldInfo() AuthLoginFields {
	return AuthLoginFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthLoginEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// ConfigChangeFields describes every field on [EventConfigChange] events.
type ConfigChangeFields struct {
	ActorID    audit.FieldInfo // required
	NewValue   audit.FieldInfo // required
	OldValue   audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Setting    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// ConfigChangeEvent builds a type-safe audit event: System configuration was modified.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type ConfigChangeEvent struct {
	fields audit.Fields
}

// NewConfigChangeEvent creates a EventConfigChange event with required fields.
func NewConfigChangeEvent(actorID any, newValue any, oldValue any, outcome any, setting any) *ConfigChangeEvent {
	return &ConfigChangeEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldNewValue: newValue,
		FieldOldValue: oldValue,
		FieldOutcome:  outcome,
		FieldSetting:  setting,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *ConfigChangeEvent) SetAction(v any) *ConfigChangeEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *ConfigChangeEvent) SetActorUID(v any) *ConfigChangeEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *ConfigChangeEvent) SetDestHost(v any) *ConfigChangeEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *ConfigChangeEvent) SetDestIP(v any) *ConfigChangeEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *ConfigChangeEvent) SetDestPort(v any) *ConfigChangeEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *ConfigChangeEvent) SetEndTime(v any) *ConfigChangeEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *ConfigChangeEvent) SetFileHash(v any) *ConfigChangeEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *ConfigChangeEvent) SetFileName(v any) *ConfigChangeEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *ConfigChangeEvent) SetFilePath(v any) *ConfigChangeEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *ConfigChangeEvent) SetFileSize(v any) *ConfigChangeEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *ConfigChangeEvent) SetMessage(v any) *ConfigChangeEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *ConfigChangeEvent) SetMethod(v any) *ConfigChangeEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *ConfigChangeEvent) SetPath(v any) *ConfigChangeEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *ConfigChangeEvent) SetProtocol(v any) *ConfigChangeEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *ConfigChangeEvent) SetReason(v any) *ConfigChangeEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *ConfigChangeEvent) SetReferrer(v any) *ConfigChangeEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *ConfigChangeEvent) SetRequestID(v any) *ConfigChangeEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *ConfigChangeEvent) SetRole(v any) *ConfigChangeEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *ConfigChangeEvent) SetSessionID(v any) *ConfigChangeEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *ConfigChangeEvent) SetSourceHost(v any) *ConfigChangeEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *ConfigChangeEvent) SetSourceIP(v any) *ConfigChangeEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *ConfigChangeEvent) SetSourcePort(v any) *ConfigChangeEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *ConfigChangeEvent) SetStartTime(v any) *ConfigChangeEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *ConfigChangeEvent) SetTargetID(v any) *ConfigChangeEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *ConfigChangeEvent) SetTargetRole(v any) *ConfigChangeEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *ConfigChangeEvent) SetTargetType(v any) *ConfigChangeEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *ConfigChangeEvent) SetTargetUID(v any) *ConfigChangeEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *ConfigChangeEvent) SetTransport(v any) *ConfigChangeEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *ConfigChangeEvent) SetUserAgent(v any) *ConfigChangeEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *ConfigChangeEvent) EventType() string { return EventConfigChange }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *ConfigChangeEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *ConfigChangeEvent) Description() string { return "System configuration was modified" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *ConfigChangeEvent) FieldInfo() ConfigChangeFields {
	return ConfigChangeFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		NewValue:   audit.FieldInfo{Name: FieldNewValue, Required: true},
		OldValue:   audit.FieldInfo{Name: FieldOldValue, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Setting:    audit.FieldInfo{Name: FieldSetting, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *ConfigChangeEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserCreateEvent builds a type-safe audit event: A new user account was created.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID any, outcome any) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *UserCreateEvent) SetAction(v any) *UserCreateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserCreateEvent) SetActorUID(v any) *UserCreateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserCreateEvent) SetDestHost(v any) *UserCreateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserCreateEvent) SetDestIP(v any) *UserCreateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserCreateEvent) SetDestPort(v any) *UserCreateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserCreateEvent) SetEndTime(v any) *UserCreateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserCreateEvent) SetFileHash(v any) *UserCreateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserCreateEvent) SetFileName(v any) *UserCreateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserCreateEvent) SetFilePath(v any) *UserCreateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserCreateEvent) SetFileSize(v any) *UserCreateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserCreateEvent) SetMessage(v any) *UserCreateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserCreateEvent) SetMethod(v any) *UserCreateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserCreateEvent) SetPath(v any) *UserCreateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserCreateEvent) SetProtocol(v any) *UserCreateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserCreateEvent) SetReason(v any) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserCreateEvent) SetReferrer(v any) *UserCreateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserCreateEvent) SetRequestID(v any) *UserCreateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserCreateEvent) SetRole(v any) *UserCreateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserCreateEvent) SetSessionID(v any) *UserCreateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserCreateEvent) SetSourceHost(v any) *UserCreateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserCreateEvent) SetSourceIP(v any) *UserCreateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserCreateEvent) SetSourcePort(v any) *UserCreateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserCreateEvent) SetStartTime(v any) *UserCreateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *UserCreateEvent) SetTargetID(v any) *UserCreateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserCreateEvent) SetTargetRole(v any) *UserCreateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserCreateEvent) SetTargetType(v any) *UserCreateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserCreateEvent) SetTargetUID(v any) *UserCreateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserCreateEvent) SetTransport(v any) *UserCreateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserCreateEvent) SetUserAgent(v any) *UserCreateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Logger.AuditEvent].
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "A new user account was created" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}
