@core @builders
Feature: Typed Event Builders
  As a library consumer using code generation, I want typed event builders
  that enforce field correctness at compile time, so that I cannot
  accidentally add the wrong field to the wrong event type.

  Typed builders are generated by audit-gen from the taxonomy YAML.
  Each event type gets a constructor (required fields as parameters),
  chainable setters (optional fields), and metadata accessors.

  Background:
    Given a standard test taxonomy

  Scenario: AuditEvent delivers event to output
    Given a logger with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value   |
      | outcome  | success |
      | actor_id | alice   |
    Then the stdout output should contain event_type "user_create"
    And the stdout output should contain field "actor_id" with value "alice"

  Scenario: AuditEvent with nil event returns error
    Given a logger with stdout output
    When I audit a nil event
    Then the last error should contain "event must not be nil"

  Scenario: NewEvent with missing required field returns error
    Given a logger with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field   | value   |
      | outcome | success |
    Then the last error should contain "missing required"

  Scenario: NewEvent with unknown event type returns error
    Given a logger with stdout output
    When I audit via NewEvent "nonexistent_event" with fields:
      | field   | value   |
      | outcome | success |
    Then the last error should contain "unknown event type"

  Scenario: AuditEvent with optional fields delivered correctly
    Given a logger with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value       |
      | outcome  | success     |
      | actor_id | alice       |
      | marker   | test-marker |
    Then the stdout output should contain field "marker" with value "test-marker"

  Scenario: Multiple AuditEvent calls deliver multiple events
    Given a logger with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value   |
      | outcome  | success |
      | actor_id | alice   |
    And I audit via NewEvent "auth_failure" with fields:
      | field    | value   |
      | outcome  | failure |
      | actor_id | unknown |
    Then the output should contain exactly 2 events
