@core @builders
Feature: Typed Event Builders
  As a library consumer using code generation, I want typed event builders
  that enforce field correctness at compile time, so that I cannot
  accidentally add the wrong field to the wrong event type.

  Typed builders are generated by audit-gen from the taxonomy YAML.
  Each event type gets a constructor (required fields as parameters),
  chainable setters (optional fields), reserved-field setters with
  library-authoritative Go types, and metadata accessors.

  These scenarios exercise the real audit-gen output committed at
  tests/bdd/steps/genfixture/audit_generated.go. The fixture taxonomy
  matches the schema; every step calls the generated constructors and
  setters directly, so a regression in audit-gen, the FieldsDonor
  contract, or the typed-setter generator surfaces here as a feature
  failure rather than an internal-test failure.

  Background:
    Given the typed-builder fixture taxonomy

  Scenario: Generated constructor + AuditEvent delivers to output
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success"
    Then the stdout output should contain event_type "user_create"
    And the stdout output should contain field "actor_id" with value "alice"
    And the stdout output should contain field "outcome" with value "success"

  Scenario: Generated string setter for declared optional field
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and marker "marker-1"
    Then the stdout output should contain field "marker" with value "marker-1"

  Scenario: Generated string setter for reserved standard field (source_ip)
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and source_ip "10.0.0.1"
    Then the stdout output should contain field "source_ip" with value "10.0.0.1"

  Scenario: Generated typed int setter (custom field, type: int)
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and session_count 42
    Then the stdout output should contain field "session_count" with value "42"

  Scenario: Generated typed time.Duration setter (custom field, type: duration)
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and retry_after "5s"
    # JSONFormatter serialises time.Duration as int64 milliseconds.
    Then the stdout output should contain field "retry_after" with value "5000"

  Scenario: Generated typed time.Time setter (reserved standard field start_time)
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and start_time "2026-04-27T12:00:00Z"
    Then the stdout output should contain field "start_time" with value "2026-04-27T12:00:00Z"

  Scenario: Multiple typed events of different types fan out together
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success"
    And I audit a typed auth_failure event with actor_id "mallory" and outcome "failure"
    Then the output should contain exactly 2 events

  Scenario: Typed builder exposes taxonomy description metadata
    Given an auditor with stdout output
    Then the typed user_create builder reports description "A new user account was created"

  Scenario: Typed builder reports category and severity from taxonomy
    Given an auditor with stdout output
    Then the typed user_create builder reports category "write" with severity 3

  Scenario: Typed builder FieldInfoMap reports required fields
    Given an auditor with stdout output
    Then the typed user_create builder FieldInfoMap has field "actor_id" required "true"
    And the typed user_create builder FieldInfoMap has field "outcome" required "true"
    And the typed user_create builder FieldInfoMap has field "marker" required "false"

  # --- #497 W2 fast-path drain pipeline: consumer-visible byte-integrity ---
  # These scenarios exercise the FieldsDonor fast path through the drain
  # pipeline. Generated builders satisfy FieldsDonor via the unexported
  # donateFields() sentinel; the auditor takes ownership of their Fields
  # map (no per-event defensive copy). BDD pins the output correctness
  # the donation contract MUST preserve under pool recycling.
  #
  # "Zero allocations" is an implementation contract, not a consumer
  # contract, and is asserted at the benchmark layer
  # (BenchmarkAudit_FastPath_PipelineOnly, _FanOut4_NoopOutputs,
  # _WithHMAC_Noop — see BENCHMARKS.md).

  Scenario: Generated builder delivers correct field values under drain pool recycling
    Given an auditor with stdout output
    When I audit a typed user_create event with actor_id "alice" and outcome "success" and marker "event-a"
    And I audit a typed user_create event with actor_id "bob" and outcome "failure" and marker "event-b"
    Then the output should contain exactly 2 events
    And the stdout output should contain field "marker" with value "event-a"
    And the stdout output should contain field "marker" with value "event-b"
