@core @builders
Feature: Typed Event Builders
  As a library consumer using code generation, I want typed event builders
  that enforce field correctness at compile time, so that I cannot
  accidentally add the wrong field to the wrong event type.

  Typed builders are generated by audit-gen from the taxonomy YAML.
  Each event type gets a constructor (required fields as parameters),
  chainable setters (optional fields), and metadata accessors.

  Background:
    Given a standard test taxonomy

  Scenario: AuditEvent delivers event to output
    Given an auditor with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value   |
      | outcome  | success |
      | actor_id | alice   |
    Then the stdout output should contain event_type "user_create"
    And the stdout output should contain field "actor_id" with value "alice"

  Scenario: AuditEvent with nil event returns error
    Given an auditor with stdout output
    When I audit a nil event
    Then the last error should contain "event must not be nil"

  Scenario: NewEvent with missing required field returns error
    Given an auditor with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field   | value   |
      | outcome | success |
    Then the last error should contain "missing required"

  Scenario: NewEvent with unknown event type returns error
    Given an auditor with stdout output
    When I audit via NewEvent "nonexistent_event" with fields:
      | field   | value   |
      | outcome | success |
    Then the last error should contain "unknown event type"

  Scenario: AuditEvent with optional fields delivered correctly
    Given an auditor with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value       |
      | outcome  | success     |
      | actor_id | alice       |
      | marker   | test-marker |
    Then the stdout output should contain field "marker" with value "test-marker"

  Scenario: Multiple AuditEvent calls deliver multiple events
    Given an auditor with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value   |
      | outcome  | success |
      | actor_id | alice   |
    And I audit via NewEvent "auth_failure" with fields:
      | field    | value   |
      | outcome  | failure |
      | actor_id | unknown |
    Then the output should contain exactly 2 events

  # --- #497 W2 fast-path drain pipeline: consumer-visible byte-integrity ---
  # These scenarios exercise the drain pipeline under the conditions
  # where #497 changed internal behaviour (shared format-cache buffer,
  # in-place post-field assembly, pool recycling) and assert that the
  # consumer-visible contract is preserved: every event delivered to
  # every output carries its correct payload byte-for-byte.
  #
  # "Zero allocations" is an implementation contract, not a consumer
  # contract, and is asserted at the benchmark layer
  # (BenchmarkAudit_FastPath_PipelineOnly, _FanOut4_NoopOutputs,
  # _WithHMAC_Noop — see BENCHMARKS.md). BDD pins the output correctness
  # that the pool-reuse machinery MUST preserve.

  Scenario: AuditEvent delivers correct field values under drain pool recycling
    Given an auditor with stdout output
    When I audit via NewEvent "user_create" with fields:
      | field    | value    |
      | outcome  | success  |
      | actor_id | alice    |
      | marker   | event-a  |
    And I audit via NewEvent "user_create" with fields:
      | field    | value   |
      | outcome  | failure |
      | actor_id | bob     |
      | marker   | event-b |
    Then the output should contain exactly 2 events
    And the stdout output should contain field "marker" with value "event-a"
    And the stdout output should contain field "marker" with value "event-b"
