// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"regexp"
	"sort"
	"strconv"
	"text/template"

	audit "github.com/axonops/go-audit"
)

// validKey matches safe taxonomy identifiers for code generation.
var validKey = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// generateOptions controls which constant groups are emitted.
type generateOptions struct {
	Package    string
	Header     string
	InputFile  string
	Types      bool
	Fields     bool
	Categories bool
}

// constantDef represents a single generated constant.
type constantDef struct {
	Name        string // Go identifier, e.g. EventSchemaRegister
	Value       string // Original string, e.g. "schema_register"
	QuotedValue string // Go string literal, e.g. `"schema_register"`
}

// templateData is the data passed to the Go template.
type templateData struct {
	Header        string
	Package       string
	Events        []constantDef
	Categories    []constantDef
	Fields        []constantDef
	HasEvents     bool
	HasCategories bool
	HasFields     bool
}

var tmpl = template.Must(template.New("audit-gen").Parse(tmplText))

const tmplText = `{{ .Header }}

package {{ .Package }}
{{ if .HasEvents }}
// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
{{- range .Events }}
	{{ .Name }} = {{ .QuotedValue }}
{{- end }}
)
{{ end }}{{ if .HasCategories }}
// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
{{- range .Categories }}
	{{ .Name }} = {{ .QuotedValue }}
{{- end }}
)
{{ end }}{{ if .HasFields }}
// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
{{- range .Fields }}
	{{ .Name }} = {{ .QuotedValue }}
{{- end }}
)
{{ end }}`

// generate produces Go source code from a taxonomy. The output is
// gofmt-formatted and deterministic (same input → byte-identical output).
func generate(w io.Writer, tax audit.Taxonomy, opts generateOptions) error {
	data, err := buildTemplateData(tax, opts)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if execErr := tmpl.Execute(&buf, data); execErr != nil {
		return fmt.Errorf("template execution: %w", execErr)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}

	if _, err := w.Write(formatted); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

func buildTemplateData(tax audit.Taxonomy, opts generateOptions) (templateData, error) {
	header := opts.Header
	if opts.InputFile != "" {
		header = fmt.Sprintf("// Code generated by audit-gen from %s; DO NOT EDIT.", opts.InputFile)
	}

	data := templateData{
		Header:  header,
		Package: opts.Package,
	}

	if opts.Types {
		var err error
		data.Events, err = buildConstants("Event", sortedKeys(tax.Events))
		if err != nil {
			return templateData{}, err
		}
		data.HasEvents = len(data.Events) > 0
	}

	if opts.Categories {
		var err error
		data.Categories, err = buildConstants("Category", sortedKeys(tax.Categories))
		if err != nil {
			return templateData{}, err
		}
		data.HasCategories = len(data.Categories) > 0
	}

	if opts.Fields {
		var err error
		data.Fields, err = buildConstants("Field", collectFieldNames(tax))
		if err != nil {
			return templateData{}, err
		}
		data.HasFields = len(data.Fields) > 0
	}

	return data, nil
}

// buildConstants creates constantDef entries from sorted keys with a
// prefix. It validates keys for code-generation safety and detects
// naming collisions.
func buildConstants(prefix string, keys []string) ([]constantDef, error) {
	nameToKey := make(map[string]string, len(keys))
	defs := make([]constantDef, 0, len(keys))
	for _, k := range keys {
		if !validKey.MatchString(k) {
			return nil, fmt.Errorf("taxonomy key %q contains characters unsafe for code generation", k)
		}
		name := prefix + toPascalCase(k)
		if prev, ok := nameToKey[name]; ok {
			return nil, fmt.Errorf("naming collision: %q and %q both produce constant %q", prev, k, name)
		}
		nameToKey[name] = k
		defs = append(defs, constantDef{
			Name:        name,
			Value:       k,
			QuotedValue: strconv.Quote(k),
		})
	}
	return defs, nil
}

// collectFieldNames returns all unique field names from the taxonomy, sorted.
func collectFieldNames(tax audit.Taxonomy) []string {
	seen := make(map[string]struct{})
	for _, def := range tax.Events {
		for _, f := range def.Required {
			seen[f] = struct{}{}
		}
		for _, f := range def.Optional {
			seen[f] = struct{}{}
		}
	}
	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
