// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

package main

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventPaymentProcess — A payment was processed
	EventPaymentProcess = "payment_process"
	// EventShutdown — Application shutting down
	EventShutdown = "shutdown"
	// EventStartup — Application started
	EventStartup = "startup"
	// EventUserCreate — A new user account was created
	EventUserCreate = "user_create"
)

// Category constants — use with Logger.EnableCategory and
// Logger.DisableCategory.
const (
	CategoryLifecycle = "lifecycle"
	CategoryWrite     = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldActorID    = "actor_id"
	FieldAmount     = "amount"
	FieldAppName    = "app_name"
	FieldCardExpiry = "card_expiry"
	FieldCardNumber = "card_number"
	FieldConfig     = "config"
	FieldDepartment = "department"
	FieldEmail      = "email"
	FieldOutcome    = "outcome"
	FieldPhone      = "phone"
	FieldReason     = "reason"
	FieldUptimeMS   = "uptime_ms"
	FieldUserName   = "user_name"
	FieldVersion    = "version"
)

// Sensitivity label constants — use with exclude_labels
// in output configuration.
const (
	// LabelFinancial — Financial and payment data
	LabelFinancial = "financial"
	// LabelPii — Personally identifiable information
	LabelPii = "pii"
)

// FieldLabels maps field names to the sensitivity labels they carry.
// Resolved from all three mechanisms: explicit annotation, global
// field mapping, and regex patterns.
var FieldLabels = map[string][]string{
	"card_expiry": {"financial"},
	"card_number": {"financial"},
	"email":       {"pii"},
	"phone":       {"pii"},
	"user_name":   {"pii"},
}

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	"payment_process": {
		Required: []string{"actor_id", "outcome"},
		Optional: []string{"amount", "card_expiry", "card_number"},
	},
	"shutdown": {
		Required: []string{"app_name"},
		Optional: []string{"reason", "uptime_ms"},
	},
	"startup": {
		Required: []string{"app_name"},
		Optional: []string{"config", "version"},
	},
	"user_create": {
		Required: []string{"actor_id", "outcome"},
		Optional: []string{"department", "email", "phone", "user_name"},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	"lifecycle": {"shutdown", "startup"},
	"write":     {"payment_process", "user_create"},
}
